/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthAccountsAddressGetResponse {
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<Box<crate::models::AuthAccountsAddressGetResponseValue>>,
}

impl AuthAccountsAddressGetResponse {
    pub fn new() -> AuthAccountsAddressGetResponse {
        AuthAccountsAddressGetResponse {
            r#type: None,
            value: None,
        }
    }
}
