/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BlocksLatestGetResponse {
    #[serde(rename = "block_meta", skip_serializing_if = "Option::is_none")]
    pub block_meta: Option<Box<crate::models::BlocksLatestGetResponseBlockMeta>>,
    #[serde(rename = "block", skip_serializing_if = "Option::is_none")]
    pub block: Option<Box<crate::models::BlocksLatestGetResponseBlock>>,
}

impl BlocksLatestGetResponse {
    pub fn new() -> BlocksLatestGetResponse {
        BlocksLatestGetResponse {
            block_meta: None,
            block: None,
        }
    }
}
