/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BlocksLatestGetResponseBlockLastCommit {
    #[serde(rename = "block_id", skip_serializing_if = "Option::is_none")]
    pub block_id: Option<Box<crate::models::BlocksLatestGetResponseBlockMetaHeaderLastBlockId>>,
    #[serde(rename = "precommits", skip_serializing_if = "Option::is_none")]
    pub precommits:
        Option<Vec<crate::models::BlocksLatestGetResponseBlockLastCommitPrecommitsInner>>,
}

impl BlocksLatestGetResponseBlockLastCommit {
    pub fn new() -> BlocksLatestGetResponseBlockLastCommit {
        BlocksLatestGetResponseBlockLastCommit {
            block_id: None,
            precommits: None,
        }
    }
}
