/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BlocksLatestGetResponseBlockMetaHeaderLastBlockId {
    #[serde(rename = "hash", skip_serializing_if = "Option::is_none")]
    pub hash: Option<String>,
    #[serde(rename = "parts", skip_serializing_if = "Option::is_none")]
    pub parts:
        Option<Box<crate::models::BlocksLatestGetResponseBlockMetaHeaderLastBlockIdParts>>,
}

impl BlocksLatestGetResponseBlockMetaHeaderLastBlockId {
    pub fn new() -> BlocksLatestGetResponseBlockMetaHeaderLastBlockId {
        BlocksLatestGetResponseBlockMetaHeaderLastBlockId {
            hash: None,
            parts: None,
        }
    }
}
