/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BlocksLatestGetResponseBlockLastCommitPrecommitsInner {
    #[serde(rename = "validator_address", skip_serializing_if = "Option::is_none")]
    pub validator_address: Option<String>,
    #[serde(rename = "validator_index", skip_serializing_if = "Option::is_none")]
    pub validator_index: Option<String>,
    #[serde(rename = "height", skip_serializing_if = "Option::is_none")]
    pub height: Option<String>,
    #[serde(rename = "round", skip_serializing_if = "Option::is_none")]
    pub round: Option<String>,
    #[serde(rename = "timestamp", skip_serializing_if = "Option::is_none")]
    pub timestamp: Option<String>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<f32>,
    #[serde(rename = "block_id", skip_serializing_if = "Option::is_none")]
    pub block_id: Option<Box<crate::models::BlocksLatestGetResponseBlockMetaHeaderLastBlockId>>,
    #[serde(rename = "signature", skip_serializing_if = "Option::is_none")]
    pub signature: Option<String>,
}

impl BlocksLatestGetResponseBlockLastCommitPrecommitsInner {
    pub fn new() -> BlocksLatestGetResponseBlockLastCommitPrecommitsInner {
        BlocksLatestGetResponseBlockLastCommitPrecommitsInner {
            validator_address: None,
            validator_index: None,
            height: None,
            round: None,
            timestamp: None,
            r#type: None,
            block_id: None,
            signature: None,
        }
    }
}
