/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DistributionDelegatorsDelegatorAddrWithdrawAddressPostRequest {
    #[serde(rename = "base_req", skip_serializing_if = "Option::is_none")]
    pub base_req: Option<Box<crate::models::BankAccountsAddressTransfersPostRequestBaseReq>>,
    /// bech32 encoded address
    #[serde(rename = "withdraw_address", skip_serializing_if = "Option::is_none")]
    pub withdraw_address: Option<String>,
}

impl DistributionDelegatorsDelegatorAddrWithdrawAddressPostRequest {
    pub fn new() -> DistributionDelegatorsDelegatorAddrWithdrawAddressPostRequest {
        DistributionDelegatorsDelegatorAddrWithdrawAddressPostRequest {
            base_req: None,
            withdraw_address: None,
        }
    }
}
