/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DistributionParametersGetResponse {
    #[serde(
        rename = "base_proposer_reward",
        skip_serializing_if = "Option::is_none"
    )]
    pub base_proposer_reward: Option<String>,
    #[serde(
        rename = "bonus_proposer_reward",
        skip_serializing_if = "Option::is_none"
    )]
    pub bonus_proposer_reward: Option<String>,
    #[serde(rename = "community_tax", skip_serializing_if = "Option::is_none")]
    pub community_tax: Option<String>,
}

impl DistributionParametersGetResponse {
    pub fn new() -> DistributionParametersGetResponse {
        DistributionParametersGetResponse {
            base_proposer_reward: None,
            bonus_proposer_reward: None,
            community_tax: None,
        }
    }
}
