/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GovProposalsProposalIdProposerGetResponse {
    #[serde(rename = "proposal_id", skip_serializing_if = "Option::is_none")]
    pub proposal_id: Option<String>,
    #[serde(rename = "proposer", skip_serializing_if = "Option::is_none")]
    pub proposer: Option<String>,
}

impl GovProposalsProposalIdProposerGetResponse {
    pub fn new() -> GovProposalsProposalIdProposerGetResponse {
        GovProposalsProposalIdProposerGetResponse {
            proposal_id: None,
            proposer: None,
        }
    }
}
