/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GovParametersTallyingGetResponse {
    #[serde(rename = "threshold", skip_serializing_if = "Option::is_none")]
    pub threshold: Option<String>,
    #[serde(rename = "veto", skip_serializing_if = "Option::is_none")]
    pub veto: Option<String>,
    #[serde(rename = "governance_penalty", skip_serializing_if = "Option::is_none")]
    pub governance_penalty: Option<String>,
}

impl GovParametersTallyingGetResponse {
    pub fn new() -> GovParametersTallyingGetResponse {
        GovParametersTallyingGetResponse {
            threshold: None,
            veto: None,
            governance_penalty: None,
        }
    }
}
