/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GovProposalsProposalIdDepositsPostRequest {
    #[serde(rename = "base_req", skip_serializing_if = "Option::is_none")]
    pub base_req: Option<Box<crate::models::BankAccountsAddressTransfersPostRequestBaseReq>>,
    /// bech32 encoded address
    #[serde(rename = "depositor", skip_serializing_if = "Option::is_none")]
    pub depositor: Option<String>,
    #[serde(rename = "amount", skip_serializing_if = "Option::is_none")]
    pub amount: Option<Vec<crate::models::TxsHashGetResponseTxFeeAmountInner>>,
}

impl GovProposalsProposalIdDepositsPostRequest {
    pub fn new() -> GovProposalsProposalIdDepositsPostRequest {
        GovProposalsProposalIdDepositsPostRequest {
            base_req: None,
            depositor: None,
            amount: None,
        }
    }
}
