/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GovProposalsParamChangePostRequest {
    #[serde(rename = "base_req", skip_serializing_if = "Option::is_none")]
    pub base_req: Option<Box<crate::models::BankAccountsAddressTransfersPostRequestBaseReq>>,
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// bech32 encoded address
    #[serde(rename = "proposer", skip_serializing_if = "Option::is_none")]
    pub proposer: Option<String>,
    #[serde(rename = "deposit", skip_serializing_if = "Option::is_none")]
    pub deposit: Option<Vec<crate::models::TxsHashGetResponseTxFeeAmountInner>>,
    #[serde(rename = "changes", skip_serializing_if = "Option::is_none")]
    pub changes: Option<Vec<crate::models::GovProposalsParamChangePostRequestChangesInner>>,
}

impl GovProposalsParamChangePostRequest {
    pub fn new() -> GovProposalsParamChangePostRequest {
        GovProposalsParamChangePostRequest {
            base_req: None,
            title: None,
            description: None,
            proposer: None,
            deposit: None,
            changes: None,
        }
    }
}
