/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GovParametersVotingGetResponse {
    #[serde(rename = "voting_period", skip_serializing_if = "Option::is_none")]
    pub voting_period: Option<String>,
}

impl GovParametersVotingGetResponse {
    pub fn new() -> GovParametersVotingGetResponse {
        GovParametersVotingGetResponse {
            voting_period: None,
        }
    }
}
