/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GovProposalsPostRequest {
    #[serde(rename = "base_req", skip_serializing_if = "Option::is_none")]
    pub base_req: Option<Box<crate::models::BankAccountsAddressTransfersPostRequestBaseReq>>,
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "proposal_type", skip_serializing_if = "Option::is_none")]
    pub proposal_type: Option<String>,
    /// bech32 encoded address
    #[serde(rename = "proposer", skip_serializing_if = "Option::is_none")]
    pub proposer: Option<String>,
    #[serde(rename = "initial_deposit", skip_serializing_if = "Option::is_none")]
    pub initial_deposit: Option<Vec<crate::models::TxsHashGetResponseTxFeeAmountInner>>,
}

impl GovProposalsPostRequest {
    pub fn new() -> GovProposalsPostRequest {
        GovProposalsPostRequest {
            base_req: None,
            title: None,
            description: None,
            proposal_type: None,
            proposer: None,
            initial_deposit: None,
        }
    }
}
