/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GovProposalsProposalIdVotesPostRequest {
    #[serde(rename = "base_req", skip_serializing_if = "Option::is_none")]
    pub base_req: Option<Box<crate::models::BankAccountsAddressTransfersPostRequestBaseReq>>,
    /// bech32 encoded address
    #[serde(rename = "voter", skip_serializing_if = "Option::is_none")]
    pub voter: Option<String>,
    #[serde(rename = "option", skip_serializing_if = "Option::is_none")]
    pub option: Option<String>,
}

impl GovProposalsProposalIdVotesPostRequest {
    pub fn new() -> GovProposalsProposalIdVotesPostRequest {
        GovProposalsProposalIdVotesPostRequest {
            base_req: None,
            voter: None,
            option: None,
        }
    }
}
