/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct NodeInfoGetResponse {
    #[serde(
        rename = "application_version",
        skip_serializing_if = "Option::is_none"
    )]
    pub application_version: Option<Box<crate::models::NodeInfoGetResponseApplicationVersion>>,
    #[serde(rename = "node_info", skip_serializing_if = "Option::is_none")]
    pub node_info: Option<Box<crate::models::NodeInfoGetResponseNodeInfo>>,
}

impl NodeInfoGetResponse {
    pub fn new() -> NodeInfoGetResponse {
        NodeInfoGetResponse {
            application_version: None,
            node_info: None,
        }
    }
}
