/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct NodeInfoGetResponseNodeInfo {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "moniker", skip_serializing_if = "Option::is_none")]
    pub moniker: Option<String>,
    #[serde(rename = "protocol_version", skip_serializing_if = "Option::is_none")]
    pub protocol_version: Option<Box<crate::models::NodeInfoGetResponseNodeInfoProtocolVersion>>,
    #[serde(rename = "network", skip_serializing_if = "Option::is_none")]
    pub network: Option<String>,
    #[serde(rename = "channels", skip_serializing_if = "Option::is_none")]
    pub channels: Option<String>,
    #[serde(rename = "listen_addr", skip_serializing_if = "Option::is_none")]
    pub listen_addr: Option<String>,
    /// Tendermint version
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
    #[serde(rename = "other", skip_serializing_if = "Option::is_none")]
    pub other: Option<Box<crate::models::NodeInfoGetResponseNodeInfoOther>>,
}

impl NodeInfoGetResponseNodeInfo {
    pub fn new() -> NodeInfoGetResponseNodeInfo {
        NodeInfoGetResponseNodeInfo {
            id: None,
            moniker: None,
            protocol_version: None,
            network: None,
            channels: None,
            listen_addr: None,
            version: None,
            other: None,
        }
    }
}
