/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct StakingDelegatorsDelegatorAddrUnbondingDelegationsValidatorAddrGetResponseEntriesInner
{
    #[serde(rename = "initial_balance", skip_serializing_if = "Option::is_none")]
    pub initial_balance: Option<String>,
    #[serde(rename = "balance", skip_serializing_if = "Option::is_none")]
    pub balance: Option<String>,
    #[serde(rename = "creation_height", skip_serializing_if = "Option::is_none")]
    pub creation_height: Option<String>,
    #[serde(rename = "min_time", skip_serializing_if = "Option::is_none")]
    pub min_time: Option<String>,
}

impl StakingDelegatorsDelegatorAddrUnbondingDelegationsValidatorAddrGetResponseEntriesInner {
    pub fn new(
    ) -> StakingDelegatorsDelegatorAddrUnbondingDelegationsValidatorAddrGetResponseEntriesInner
    {
        StakingDelegatorsDelegatorAddrUnbondingDelegationsValidatorAddrGetResponseEntriesInner {
            initial_balance: None,
            balance: None,
            creation_height: None,
            min_time: None,
        }
    }
}
