/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct StakingDelegatorsDelegatorAddrValidatorsGetResponseInnerCommission {
    #[serde(rename = "rate", skip_serializing_if = "Option::is_none")]
    pub rate: Option<String>,
    #[serde(rename = "max_rate", skip_serializing_if = "Option::is_none")]
    pub max_rate: Option<String>,
    #[serde(rename = "max_change_rate", skip_serializing_if = "Option::is_none")]
    pub max_change_rate: Option<String>,
    #[serde(rename = "update_time", skip_serializing_if = "Option::is_none")]
    pub update_time: Option<String>,
}

impl StakingDelegatorsDelegatorAddrValidatorsGetResponseInnerCommission {
    pub fn new() -> StakingDelegatorsDelegatorAddrValidatorsGetResponseInnerCommission {
        StakingDelegatorsDelegatorAddrValidatorsGetResponseInnerCommission {
            rate: None,
            max_rate: None,
            max_change_rate: None,
            update_time: None,
        }
    }
}
