/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct StakingParametersGetResponse {
    #[serde(
        rename = "inflation_rate_change",
        skip_serializing_if = "Option::is_none"
    )]
    pub inflation_rate_change: Option<String>,
    #[serde(rename = "inflation_max", skip_serializing_if = "Option::is_none")]
    pub inflation_max: Option<String>,
    #[serde(rename = "inflation_min", skip_serializing_if = "Option::is_none")]
    pub inflation_min: Option<String>,
    #[serde(rename = "goal_bonded", skip_serializing_if = "Option::is_none")]
    pub goal_bonded: Option<String>,
    #[serde(rename = "unbonding_time", skip_serializing_if = "Option::is_none")]
    pub unbonding_time: Option<String>,
    #[serde(rename = "max_validators", skip_serializing_if = "Option::is_none")]
    pub max_validators: Option<i32>,
    #[serde(rename = "bond_denom", skip_serializing_if = "Option::is_none")]
    pub bond_denom: Option<String>,
}

impl StakingParametersGetResponse {
    pub fn new() -> StakingParametersGetResponse {
        StakingParametersGetResponse {
            inflation_rate_change: None,
            inflation_max: None,
            inflation_min: None,
            goal_bonded: None,
            unbonding_time: None,
            max_validators: None,
            bond_denom: None,
        }
    }
}
