/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct StakingDelegatorsDelegatorAddrValidatorsGetResponseInnerDescription {
    #[serde(rename = "moniker", skip_serializing_if = "Option::is_none")]
    pub moniker: Option<String>,
    #[serde(rename = "identity", skip_serializing_if = "Option::is_none")]
    pub identity: Option<String>,
    #[serde(rename = "website", skip_serializing_if = "Option::is_none")]
    pub website: Option<String>,
    #[serde(rename = "security_contact", skip_serializing_if = "Option::is_none")]
    pub security_contact: Option<String>,
    #[serde(rename = "details", skip_serializing_if = "Option::is_none")]
    pub details: Option<String>,
}

impl StakingDelegatorsDelegatorAddrValidatorsGetResponseInnerDescription {
    pub fn new() -> StakingDelegatorsDelegatorAddrValidatorsGetResponseInnerDescription {
        StakingDelegatorsDelegatorAddrValidatorsGetResponseInnerDescription {
            moniker: None,
            identity: None,
            website: None,
            security_contact: None,
            details: None,
        }
    }
}
