/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct StakingDelegatorsDelegatorAddrRedelegationsPostRequest {
    #[serde(rename = "base_req", skip_serializing_if = "Option::is_none")]
    pub base_req: Option<Box<crate::models::BankAccountsAddressTransfersPostRequestBaseReq>>,
    /// bech32 encoded address
    #[serde(rename = "delegator_address", skip_serializing_if = "Option::is_none")]
    pub delegator_address: Option<String>,
    /// bech32 encoded address
    #[serde(
        rename = "validator_src_addressess",
        skip_serializing_if = "Option::is_none"
    )]
    pub validator_src_addressess: Option<String>,
    /// bech32 encoded address
    #[serde(
        rename = "validator_dst_address",
        skip_serializing_if = "Option::is_none"
    )]
    pub validator_dst_address: Option<String>,
    #[serde(rename = "shares", skip_serializing_if = "Option::is_none")]
    pub shares: Option<String>,
}

impl StakingDelegatorsDelegatorAddrRedelegationsPostRequest {
    pub fn new() -> StakingDelegatorsDelegatorAddrRedelegationsPostRequest {
        StakingDelegatorsDelegatorAddrRedelegationsPostRequest {
            base_req: None,
            delegator_address: None,
            validator_src_addressess: None,
            validator_dst_address: None,
            shares: None,
        }
    }
}
