/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct StakingPoolGetResponse {
    #[serde(rename = "loose_tokens", skip_serializing_if = "Option::is_none")]
    pub loose_tokens: Option<String>,
    #[serde(rename = "bonded_tokens", skip_serializing_if = "Option::is_none")]
    pub bonded_tokens: Option<String>,
    #[serde(
        rename = "inflation_last_time",
        skip_serializing_if = "Option::is_none"
    )]
    pub inflation_last_time: Option<String>,
    #[serde(rename = "inflation", skip_serializing_if = "Option::is_none")]
    pub inflation: Option<String>,
    #[serde(
        rename = "date_last_commission_reset",
        skip_serializing_if = "Option::is_none"
    )]
    pub date_last_commission_reset: Option<String>,
    #[serde(rename = "prev_bonded_shares", skip_serializing_if = "Option::is_none")]
    pub prev_bonded_shares: Option<String>,
}

impl StakingPoolGetResponse {
    pub fn new() -> StakingPoolGetResponse {
        StakingPoolGetResponse {
            loose_tokens: None,
            bonded_tokens: None,
            inflation_last_time: None,
            inflation: None,
            date_last_commission_reset: None,
            prev_bonded_shares: None,
        }
    }
}
