/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SyncingGetResponse {
    #[serde(rename = "syncing", skip_serializing_if = "Option::is_none")]
    pub syncing: Option<bool>,
}

impl SyncingGetResponse {
    pub fn new() -> SyncingGetResponse {
        SyncingGetResponse { syncing: None }
    }
}
