/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TxsEncodePostRequest {
    #[serde(rename = "tx", skip_serializing_if = "Option::is_none")]
    pub tx: Option<Box<crate::models::TxsHashGetResponseTx>>,
}

impl TxsEncodePostRequest {
    pub fn new() -> TxsEncodePostRequest {
        TxsEncodePostRequest { tx: None }
    }
}
