/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TxsPostRequest {
    #[serde(rename = "tx", skip_serializing_if = "Option::is_none")]
    pub tx: Option<Box<crate::models::TxsHashGetResponseTx>>,
    #[serde(rename = "mode", skip_serializing_if = "Option::is_none")]
    pub mode: Option<String>,
    #[serde(rename = "sequences", skip_serializing_if = "Option::is_none")]
    pub sequences: Option<Vec<String>>,
    /// bech32 encoded address
    #[serde(rename = "fee_granter", skip_serializing_if = "Option::is_none")]
    pub fee_granter: Option<String>,
}

impl TxsPostRequest {
    pub fn new() -> TxsPostRequest {
        TxsPostRequest {
            tx: None,
            mode: None,
            sequences: None,
            fee_granter: None,
        }
    }
}
