/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TxsHashGetResponseTx {
    #[serde(rename = "msg", skip_serializing_if = "Option::is_none")]
    pub msg: Option<Vec<String>>,
    #[serde(rename = "fee", skip_serializing_if = "Option::is_none")]
    pub fee: Option<Box<crate::models::TxsHashGetResponseTxFee>>,
    #[serde(rename = "memo", skip_serializing_if = "Option::is_none")]
    pub memo: Option<String>,
    #[serde(rename = "signature", skip_serializing_if = "Option::is_none")]
    pub signature: Option<Box<crate::models::TxsHashGetResponseTxSignature>>,
}

impl TxsHashGetResponseTx {
    pub fn new() -> TxsHashGetResponseTx {
        TxsHashGetResponseTx {
            msg: None,
            fee: None,
            memo: None,
            signature: None,
        }
    }
}
