/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TxsPostResponse {
    #[serde(rename = "check_tx", skip_serializing_if = "Option::is_none")]
    pub check_tx: Option<Box<crate::models::TxsPostResponseCheckTx>>,
    #[serde(rename = "deliver_tx", skip_serializing_if = "Option::is_none")]
    pub deliver_tx: Option<Box<crate::models::TxsPostResponseDeliverTx>>,
    #[serde(rename = "hash", skip_serializing_if = "Option::is_none")]
    pub hash: Option<String>,
    #[serde(rename = "height", skip_serializing_if = "Option::is_none")]
    pub height: Option<i32>,
}

impl TxsPostResponse {
    pub fn new() -> TxsPostResponse {
        TxsPostResponse {
            check_tx: None,
            deliver_tx: None,
            hash: None,
            height: None,
        }
    }
}
