/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TxsHashGetResponseTxFee {
    #[serde(rename = "gas", skip_serializing_if = "Option::is_none")]
    pub gas: Option<String>,
    #[serde(rename = "amount", skip_serializing_if = "Option::is_none")]
    pub amount: Option<Vec<crate::models::TxsHashGetResponseTxFeeAmountInner>>,
}

impl TxsHashGetResponseTxFee {
    pub fn new() -> TxsHashGetResponseTxFee {
        TxsHashGetResponseTxFee {
            gas: None,
            amount: None,
        }
    }
}
