/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ValidatorsetsLatestGetResponse {
    #[serde(rename = "block_height", skip_serializing_if = "Option::is_none")]
    pub block_height: Option<String>,
    #[serde(rename = "validators", skip_serializing_if = "Option::is_none")]
    pub validators: Option<Vec<crate::models::ValidatorsetsLatestGetResponseValidatorsInner>>,
}

impl ValidatorsetsLatestGetResponse {
    pub fn new() -> ValidatorsetsLatestGetResponse {
        ValidatorsetsLatestGetResponse {
            block_height: None,
            validators: None,
        }
    }
}
