/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct WasmContractContractAddressPostRequest {
    #[serde(rename = "base_req", skip_serializing_if = "Option::is_none")]
    pub base_req: Option<Box<crate::models::BankAccountsAddressTransfersPostRequestBaseReq>>,
    #[serde(rename = "coins", skip_serializing_if = "Option::is_none")]
    pub coins: Option<Vec<crate::models::TxsHashGetResponseTxFeeAmountInner>>,
    #[serde(rename = "exec_msg", skip_serializing_if = "Option::is_none")]
    pub exec_msg: Option<String>,
}

impl WasmContractContractAddressPostRequest {
    pub fn new() -> WasmContractContractAddressPostRequest {
        WasmContractContractAddressPostRequest {
            base_req: None,
            coins: None,
            exec_msg: None,
        }
    }
}
