/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

/// AbsoluteTxPositionCanBeUsedToSortContracts : Updated Tx position when the operation was executed.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AbsoluteTxPositionCanBeUsedToSortContracts {
    #[serde(rename = "block_height", skip_serializing_if = "Option::is_none")]
    pub block_height: Option<String>,
    #[serde(rename = "tx_index", skip_serializing_if = "Option::is_none")]
    pub tx_index: Option<String>,
}

impl AbsoluteTxPositionCanBeUsedToSortContracts {
    /// Updated Tx position when the operation was executed.
    pub fn new() -> AbsoluteTxPositionCanBeUsedToSortContracts {
        AbsoluteTxPositionCanBeUsedToSortContracts {
            block_height: None,
            tx_index: None,
        }
    }
}
