/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

/// AccountResponse : QueryAccountResponse is the response type for the Query/Account RPC method.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AccountResponse {
    #[serde(rename = "account", skip_serializing_if = "Option::is_none")]
    pub account: Option<Box<crate::models::AccountsAreTheExistingAccountsInner>>,
}

impl AccountResponse {
    /// QueryAccountResponse is the response type for the Query/Account RPC method.
    pub fn new() -> AccountResponse {
        AccountResponse { account: None }
    }
}
