/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

/// AccountsResponse : QueryAccountsResponse is the response type for the Query/Accounts RPC method.  Since: cosmos-sdk 0.43

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AccountsResponse {
    #[serde(rename = "accounts", skip_serializing_if = "Option::is_none")]
    pub accounts: Option<Vec<crate::models::AccountsAreTheExistingAccountsInner>>,
    #[serde(rename = "pagination", skip_serializing_if = "Option::is_none")]
    pub pagination: Option<Box<crate::models::AccountsResponsePagination>>,
}

impl AccountsResponse {
    /// QueryAccountsResponse is the response type for the Query/Accounts RPC method.  Since: cosmos-sdk 0.43
    pub fn new() -> AccountsResponse {
        AccountsResponse {
            accounts: None,
            pagination: None,
        }
    }
}
