/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AddressByLabelResponse {
    #[serde(rename = "contract_address", skip_serializing_if = "Option::is_none")]
    pub contract_address: Option<String>,
}

impl AddressByLabelResponse {
    pub fn new() -> AddressByLabelResponse {
        AddressByLabelResponse {
            contract_address: None,
        }
    }
}
