/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AllBalancesDefaultResponse {
    #[serde(rename = "error", skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
    #[serde(rename = "code", skip_serializing_if = "Option::is_none")]
    pub code: Option<i32>,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    #[serde(rename = "details", skip_serializing_if = "Option::is_none")]
    pub details: Option<Vec<crate::models::AllBalancesDefaultResponseDetailsInner>>,
}

impl AllBalancesDefaultResponse {
    pub fn new() -> AllBalancesDefaultResponse {
        AllBalancesDefaultResponse {
            error: None,
            code: None,
            message: None,
            details: None,
        }
    }
}
