/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AllBalancesDefaultResponseDetailsInner {
    #[serde(rename = "type_url", skip_serializing_if = "Option::is_none")]
    pub type_url: Option<String>,
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
}

impl AllBalancesDefaultResponseDetailsInner {
    pub fn new() -> AllBalancesDefaultResponseDetailsInner {
        AllBalancesDefaultResponseDetailsInner {
            type_url: None,
            value: None,
        }
    }
}
