/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

/// AllEvidenceResponse : QueryAllEvidenceResponse is the response type for the Query/AllEvidence RPC method.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AllEvidenceResponse {
    /// evidence returns all evidences.
    #[serde(rename = "evidence", skip_serializing_if = "Option::is_none")]
    pub evidence: Option<Vec<crate::models::AccountsAreTheExistingAccountsInner>>,
    #[serde(rename = "pagination", skip_serializing_if = "Option::is_none")]
    pub pagination: Option<Box<crate::models::AccountsResponsePagination>>,
}

impl AllEvidenceResponse {
    /// QueryAllEvidenceResponse is the response type for the Query/AllEvidence RPC method.
    pub fn new() -> AllEvidenceResponse {
        AllEvidenceResponse {
            evidence: None,
            pagination: None,
        }
    }
}
