/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

/// BankParamsResponse : QueryParamsResponse defines the response type for querying x/bank parameters.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BankParamsResponse {
    #[serde(rename = "params", skip_serializing_if = "Option::is_none")]
    pub params: Option<Box<crate::models::BankParamsResponseParams>>,
}

impl BankParamsResponse {
    /// QueryParamsResponse defines the response type for querying x/bank parameters.
    pub fn new() -> BankParamsResponse {
        BankParamsResponse { params: None }
    }
}
