/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

/// BasicBlockInfo : Consensus captures the consensus rules for processing a block in the blockchain, including all blockchain data structures and the rules of the application's state transition machine.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BasicBlockInfo {
    #[serde(rename = "block", skip_serializing_if = "Option::is_none")]
    pub block: Option<String>,
    #[serde(rename = "app", skip_serializing_if = "Option::is_none")]
    pub app: Option<String>,
}

impl BasicBlockInfo {
    /// Consensus captures the consensus rules for processing a block in the blockchain, including all blockchain data structures and the rules of the application's state transition machine.
    pub fn new() -> BasicBlockInfo {
        BasicBlockInfo {
            block: None,
            app: None,
        }
    }
}
