/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

/// ChannelResponse : QueryChannelResponse is the response type for the Query/Channel RPC method. Besides the Channel end, it includes a proof and the height from which the proof was retrieved.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChannelResponse {
    #[serde(rename = "channel", skip_serializing_if = "Option::is_none")]
    pub channel: Option<Box<crate::models::ChannelAssociatedWithTheRequestIdentifiers>>,
    #[serde(rename = "proof", skip_serializing_if = "Option::is_none")]
    pub proof: Option<String>,
    #[serde(rename = "proof_height", skip_serializing_if = "Option::is_none")]
    pub proof_height: Option<Box<crate::models::HeightAtWhichTheProofWasRetrieved>>,
}

impl ChannelResponse {
    /// QueryChannelResponse is the response type for the Query/Channel RPC method. Besides the Channel end, it includes a proof and the height from which the proof was retrieved.
    pub fn new() -> ChannelResponse {
        ChannelResponse {
            channel: None,
            proof: None,
            proof_height: None,
        }
    }
}
