/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

/// ClientParamsResponseParams : params defines the parameters of the module.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClientParamsResponseParams {
    /// allowed_clients defines the list of allowed client state types.
    #[serde(rename = "allowed_clients", skip_serializing_if = "Option::is_none")]
    pub allowed_clients: Option<Vec<String>>,
}

impl ClientParamsResponseParams {
    /// params defines the parameters of the module.
    pub fn new() -> ClientParamsResponseParams {
        ClientParamsResponseParams {
            allowed_clients: None,
        }
    }
}
