/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

/// ClientStatusResponse : QueryClientStatusResponse is the response type for the Query/ClientStatus RPC method. It returns the current status of the IBC client.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClientStatusResponse {
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
}

impl ClientStatusResponse {
    /// QueryClientStatusResponse is the response type for the Query/ClientStatus RPC method. It returns the current status of the IBC client.
    pub fn new() -> ClientStatusResponse {
        ClientStatusResponse { status: None }
    }
}
