/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CodeInfo {
    #[serde(rename = "code_hash", skip_serializing_if = "Option::is_none")]
    pub code_hash: Option<String>,
    #[serde(rename = "creator", skip_serializing_if = "Option::is_none")]
    pub creator: Option<String>,
}

impl CodeInfo {
    pub fn new() -> CodeInfo {
        CodeInfo {
            code_hash: None,
            creator: None,
        }
    }
}
