/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

/// ConnectionsResponseConnectionsInnerCounterparty : counterparty chain associated with this connection.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConnectionsResponseConnectionsInnerCounterparty {
    /// identifies the client on the counterparty chain associated with a given connection.
    #[serde(rename = "client_id", skip_serializing_if = "Option::is_none")]
    pub client_id: Option<String>,
    /// identifies the connection end on the counterparty chain associated with a given connection.
    #[serde(rename = "connection_id", skip_serializing_if = "Option::is_none")]
    pub connection_id: Option<String>,
    #[serde(rename = "prefix", skip_serializing_if = "Option::is_none")]
    pub prefix: Option<Box<crate::models::MerklePrefixIsMerklePathPrefixedToTheKeyTheConstructedKeyFromThePathAndTheKeyWillBeAppendPathKeyPathAppendPathKeyPrefixKey>>,
}

impl ConnectionsResponseConnectionsInnerCounterparty {
    /// counterparty chain associated with this connection.
    pub fn new() -> ConnectionsResponseConnectionsInnerCounterparty {
        ConnectionsResponseConnectionsInnerCounterparty {
            client_id: None,
            connection_id: None,
            prefix: None,
        }
    }
}
