/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

/// ControllerParamsResponse : QueryParamsResponse is the response type for the Query/Params RPC method.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ControllerParamsResponse {
    #[serde(rename = "params", skip_serializing_if = "Option::is_none")]
    pub params: Option<Box<crate::models::ControllerParamsResponseParams>>,
}

impl ControllerParamsResponse {
    /// QueryParamsResponse is the response type for the Query/Params RPC method.
    pub fn new() -> ControllerParamsResponse {
        ControllerParamsResponse { params: None }
    }
}
