/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

/// CosmosGovV1beta1VoteOption : VoteOption enumerates the valid vote options for a given governance proposal.   - VOTE_OPTION_UNSPECIFIED: VOTE_OPTION_UNSPECIFIED defines a no-op vote option.  - VOTE_OPTION_YES: VOTE_OPTION_YES defines a yes vote option.  - VOTE_OPTION_ABSTAIN: VOTE_OPTION_ABSTAIN defines an abstain vote option.  - VOTE_OPTION_NO: VOTE_OPTION_NO defines a no vote option.  - VOTE_OPTION_NO_WITH_VETO: VOTE_OPTION_NO_WITH_VETO defines a no with veto vote option.

/// VoteOption enumerates the valid vote options for a given governance proposal.   - VOTE_OPTION_UNSPECIFIED: VOTE_OPTION_UNSPECIFIED defines a no-op vote option.  - VOTE_OPTION_YES: VOTE_OPTION_YES defines a yes vote option.  - VOTE_OPTION_ABSTAIN: VOTE_OPTION_ABSTAIN defines an abstain vote option.  - VOTE_OPTION_NO: VOTE_OPTION_NO defines a no vote option.  - VOTE_OPTION_NO_WITH_VETO: VOTE_OPTION_NO_WITH_VETO defines a no with veto vote option.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CosmosGovV1beta1VoteOption {
    #[serde(rename = "VOTE_OPTION_UNSPECIFIED")]
    Unspecified,
    #[serde(rename = "VOTE_OPTION_YES")]
    Yes,
    #[serde(rename = "VOTE_OPTION_ABSTAIN")]
    Abstain,
    #[serde(rename = "VOTE_OPTION_NO")]
    No,
    #[serde(rename = "VOTE_OPTION_NO_WITH_VETO")]
    NoWithVeto,
}

impl ToString for CosmosGovV1beta1VoteOption {
    fn to_string(&self) -> String {
        match self {
            Self::Unspecified => String::from("VOTE_OPTION_UNSPECIFIED"),
            Self::Yes => String::from("VOTE_OPTION_YES"),
            Self::Abstain => String::from("VOTE_OPTION_ABSTAIN"),
            Self::No => String::from("VOTE_OPTION_NO"),
            Self::NoWithVeto => String::from("VOTE_OPTION_NO_WITH_VETO"),
        }
    }
}

impl Default for CosmosGovV1beta1VoteOption {
    fn default() -> CosmosGovV1beta1VoteOption {
        Self::Unspecified
    }
}
