/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

/// CosmosGovV1beta1QueryDepositResponse : QueryDepositResponse is the response type for the Query/Deposit RPC method.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosGovV1beta1QueryDepositResponse {
    #[serde(rename = "deposit", skip_serializing_if = "Option::is_none")]
    pub deposit: Option<Box<crate::models::DepositsResponseDepositsInner>>,
}

impl CosmosGovV1beta1QueryDepositResponse {
    /// QueryDepositResponse is the response type for the Query/Deposit RPC method.
    pub fn new() -> CosmosGovV1beta1QueryDepositResponse {
        CosmosGovV1beta1QueryDepositResponse { deposit: None }
    }
}
