/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

/// CosmosBankV1beta1Metadata : Metadata represents a struct that describes a basic token.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosBankV1beta1Metadata {
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "denom_units", skip_serializing_if = "Option::is_none")]
    pub denom_units:
        Option<Vec<crate::models::DenomUnitsRepresentsTheListOfDenomUnitSForAGivenCoinInner>>,
    /// base represents the base denom (should be the DenomUnit with exponent = 0).
    #[serde(rename = "base", skip_serializing_if = "Option::is_none")]
    pub base: Option<String>,
    /// display indicates the suggested denom that should be displayed in clients.
    #[serde(rename = "display", skip_serializing_if = "Option::is_none")]
    pub display: Option<String>,
    /// Since: cosmos-sdk 0.43
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// symbol is the token symbol usually shown on exchanges (eg: ATOM). This can be the same as the display.  Since: cosmos-sdk 0.43
    #[serde(rename = "symbol", skip_serializing_if = "Option::is_none")]
    pub symbol: Option<String>,
}

impl CosmosBankV1beta1Metadata {
    /// Metadata represents a struct that describes a basic token.
    pub fn new() -> CosmosBankV1beta1Metadata {
        CosmosBankV1beta1Metadata {
            description: None,
            denom_units: None,
            base: None,
            display: None,
            name: None,
            symbol: None,
        }
    }
}
