/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

/// CosmosTxV1beta1TxBody : TxBody is the body of a transaction that all signers sign over.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosTxV1beta1TxBody {
    /// messages is a list of messages to be executed. The required signers of those messages define the number and order of elements in AuthInfo's signer_infos and Tx's signatures. Each required signer address is added to the list only the first time it occurs. By convention, the first required signer (usually from the first message) is referred to as the primary signer and pays the fee for the whole transaction.
    #[serde(rename = "messages", skip_serializing_if = "Option::is_none")]
    pub messages: Option<Vec<crate::models::AccountsAreTheExistingAccountsInner>>,
    /// memo is any arbitrary note/comment to be added to the transaction. WARNING: in clients, any publicly exposed text should not be called memo, but should be called `note` instead (see https://github.com/cosmos/cosmos-sdk/issues/9122).
    #[serde(rename = "memo", skip_serializing_if = "Option::is_none")]
    pub memo: Option<String>,
    #[serde(rename = "timeout_height", skip_serializing_if = "Option::is_none")]
    pub timeout_height: Option<String>,
    #[serde(rename = "extension_options", skip_serializing_if = "Option::is_none")]
    pub extension_options: Option<Vec<crate::models::AccountsAreTheExistingAccountsInner>>,
    #[serde(
        rename = "non_critical_extension_options",
        skip_serializing_if = "Option::is_none"
    )]
    pub non_critical_extension_options:
        Option<Vec<crate::models::AccountsAreTheExistingAccountsInner>>,
}

impl CosmosTxV1beta1TxBody {
    /// TxBody is the body of a transaction that all signers sign over.
    pub fn new() -> CosmosTxV1beta1TxBody {
        CosmosTxV1beta1TxBody {
            messages: None,
            memo: None,
            timeout_height: None,
            extension_options: None,
            non_critical_extension_options: None,
        }
    }
}
