/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

/// CosmosBaseAbciV1beta1StringEvent : StringEvent defines en Event object wrapper where all the attributes contain key/value pairs that are strings instead of raw bytes.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosBaseAbciV1beta1StringEvent {
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    #[serde(rename = "attributes", skip_serializing_if = "Option::is_none")]
    pub attributes: Option<
        Vec<crate::models::GetTxsEventResponseTxResponsesInnerLogsInnerEventsInnerAttributesInner>,
    >,
}

impl CosmosBaseAbciV1beta1StringEvent {
    /// StringEvent defines en Event object wrapper where all the attributes contain key/value pairs that are strings instead of raw bytes.
    pub fn new() -> CosmosBaseAbciV1beta1StringEvent {
        CosmosBaseAbciV1beta1StringEvent {
            r#type: None,
            attributes: None,
        }
    }
}
