/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

/// CosmosDistributionV1beta1QueryCommunityPoolResponse : QueryCommunityPoolResponse is the response type for the Query/CommunityPool RPC method.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosDistributionV1beta1QueryCommunityPoolResponse {
    /// pool defines community pool's coins.
    #[serde(rename = "pool", skip_serializing_if = "Option::is_none")]
    pub pool: Option<Vec<crate::models::CommunityPoolResponsePoolInner>>,
}

impl CosmosDistributionV1beta1QueryCommunityPoolResponse {
    /// QueryCommunityPoolResponse is the response type for the Query/CommunityPool RPC method.
    pub fn new() -> CosmosDistributionV1beta1QueryCommunityPoolResponse {
        CosmosDistributionV1beta1QueryCommunityPoolResponse { pool: None }
    }
}
