/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

/// CosmosBankV1beta1QueryDenomsMetadataResponse : QueryDenomsMetadataResponse is the response type for the Query/DenomsMetadata RPC method.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosBankV1beta1QueryDenomsMetadataResponse {
    /// metadata provides the client information for all the registered tokens.
    #[serde(rename = "metadatas", skip_serializing_if = "Option::is_none")]
    pub metadatas: Option<Vec<crate::models::DenomsMetadataResponseMetadatasInner>>,
    #[serde(rename = "pagination", skip_serializing_if = "Option::is_none")]
    pub pagination: Option<Box<crate::models::AccountsResponsePagination>>,
}

impl CosmosBankV1beta1QueryDenomsMetadataResponse {
    /// QueryDenomsMetadataResponse is the response type for the Query/DenomsMetadata RPC method.
    pub fn new() -> CosmosBankV1beta1QueryDenomsMetadataResponse {
        CosmosBankV1beta1QueryDenomsMetadataResponse {
            metadatas: None,
            pagination: None,
        }
    }
}
