/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

/// CosmosBankV1beta1SendEnabled : SendEnabled maps coin denom to a send_enabled status (whether a denom is sendable).

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosBankV1beta1SendEnabled {
    #[serde(rename = "denom", skip_serializing_if = "Option::is_none")]
    pub denom: Option<String>,
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
}

impl CosmosBankV1beta1SendEnabled {
    /// SendEnabled maps coin denom to a send_enabled status (whether a denom is sendable).
    pub fn new() -> CosmosBankV1beta1SendEnabled {
        CosmosBankV1beta1SendEnabled {
            denom: None,
            enabled: None,
        }
    }
}
