/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

/// CosmosUpgradeV1beta1QueryCurrentPlanResponse : QueryCurrentPlanResponse is the response type for the Query/CurrentPlan RPC method.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosUpgradeV1beta1QueryCurrentPlanResponse {
    #[serde(rename = "plan", skip_serializing_if = "Option::is_none")]
    pub plan: Option<Box<crate::models::CurrentPlanResponsePlan>>,
}

impl CosmosUpgradeV1beta1QueryCurrentPlanResponse {
    /// QueryCurrentPlanResponse is the response type for the Query/CurrentPlan RPC method.
    pub fn new() -> CosmosUpgradeV1beta1QueryCurrentPlanResponse {
        CosmosUpgradeV1beta1QueryCurrentPlanResponse { plan: None }
    }
}
