/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

/// CosmosDistributionV1beta1Params : Params defines the set of params for the distribution module.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosDistributionV1beta1Params {
    #[serde(rename = "community_tax", skip_serializing_if = "Option::is_none")]
    pub community_tax: Option<String>,
    #[serde(
        rename = "base_proposer_reward",
        skip_serializing_if = "Option::is_none"
    )]
    pub base_proposer_reward: Option<String>,
    #[serde(
        rename = "bonus_proposer_reward",
        skip_serializing_if = "Option::is_none"
    )]
    pub bonus_proposer_reward: Option<String>,
    #[serde(
        rename = "withdraw_addr_enabled",
        skip_serializing_if = "Option::is_none"
    )]
    pub withdraw_addr_enabled: Option<bool>,
    #[serde(
        rename = "secret_foundation_tax",
        skip_serializing_if = "Option::is_none"
    )]
    pub secret_foundation_tax: Option<String>,
    #[serde(
        rename = "secret_foundation_address",
        skip_serializing_if = "Option::is_none"
    )]
    pub secret_foundation_address: Option<String>,
    #[serde(
        rename = "minimum_restake_threshold",
        skip_serializing_if = "Option::is_none"
    )]
    pub minimum_restake_threshold: Option<String>,
    #[serde(rename = "restake_period", skip_serializing_if = "Option::is_none")]
    pub restake_period: Option<String>,
}

impl CosmosDistributionV1beta1Params {
    /// Params defines the set of params for the distribution module.
    pub fn new() -> CosmosDistributionV1beta1Params {
        CosmosDistributionV1beta1Params {
            community_tax: None,
            base_proposer_reward: None,
            bonus_proposer_reward: None,
            withdraw_addr_enabled: None,
            secret_foundation_tax: None,
            secret_foundation_address: None,
            minimum_restake_threshold: None,
            restake_period: None,
        }
    }
}
