/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

/// CosmosBaseTendermintV1beta1VersionInfo : VersionInfo is the type for the GetNodeInfoResponse message.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosBaseTendermintV1beta1VersionInfo {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "app_name", skip_serializing_if = "Option::is_none")]
    pub app_name: Option<String>,
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
    #[serde(rename = "git_commit", skip_serializing_if = "Option::is_none")]
    pub git_commit: Option<String>,
    #[serde(rename = "build_tags", skip_serializing_if = "Option::is_none")]
    pub build_tags: Option<String>,
    #[serde(rename = "go_version", skip_serializing_if = "Option::is_none")]
    pub go_version: Option<String>,
    #[serde(rename = "build_deps", skip_serializing_if = "Option::is_none")]
    pub build_deps: Option<Vec<crate::models::ModuleIsTheTypeForVersionInfo>>,
    #[serde(rename = "cosmos_sdk_version", skip_serializing_if = "Option::is_none")]
    pub cosmos_sdk_version: Option<String>,
}

impl CosmosBaseTendermintV1beta1VersionInfo {
    /// VersionInfo is the type for the GetNodeInfoResponse message.
    pub fn new() -> CosmosBaseTendermintV1beta1VersionInfo {
        CosmosBaseTendermintV1beta1VersionInfo {
            name: None,
            app_name: None,
            version: None,
            git_commit: None,
            build_tags: None,
            go_version: None,
            build_deps: None,
            cosmos_sdk_version: None,
        }
    }
}
