/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

/// CosmosStakingV1beta1Pool : Pool is used for tracking bonded and not-bonded token supply of the bond denomination.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosStakingV1beta1Pool {
    #[serde(rename = "not_bonded_tokens", skip_serializing_if = "Option::is_none")]
    pub not_bonded_tokens: Option<String>,
    #[serde(rename = "bonded_tokens", skip_serializing_if = "Option::is_none")]
    pub bonded_tokens: Option<String>,
}

impl CosmosStakingV1beta1Pool {
    /// Pool is used for tracking bonded and not-bonded token supply of the bond denomination.
    pub fn new() -> CosmosStakingV1beta1Pool {
        CosmosStakingV1beta1Pool {
            not_bonded_tokens: None,
            bonded_tokens: None,
        }
    }
}
