/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

/// CosmosTxV1beta1BroadcastMode : BroadcastMode specifies the broadcast mode for the TxService.Broadcast RPC method.   - BROADCAST_MODE_UNSPECIFIED: zero-value for mode ordering  - BROADCAST_MODE_BLOCK: BROADCAST_MODE_BLOCK defines a tx broadcasting mode where the client waits for the tx to be committed in a block.  - BROADCAST_MODE_SYNC: BROADCAST_MODE_SYNC defines a tx broadcasting mode where the client waits for a CheckTx execution response only.  - BROADCAST_MODE_ASYNC: BROADCAST_MODE_ASYNC defines a tx broadcasting mode where the client returns immediately.

/// BroadcastMode specifies the broadcast mode for the TxService.Broadcast RPC method.   - BROADCAST_MODE_UNSPECIFIED: zero-value for mode ordering  - BROADCAST_MODE_BLOCK: BROADCAST_MODE_BLOCK defines a tx broadcasting mode where the client waits for the tx to be committed in a block.  - BROADCAST_MODE_SYNC: BROADCAST_MODE_SYNC defines a tx broadcasting mode where the client waits for a CheckTx execution response only.  - BROADCAST_MODE_ASYNC: BROADCAST_MODE_ASYNC defines a tx broadcasting mode where the client returns immediately.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CosmosTxV1beta1BroadcastMode {
    #[serde(rename = "BROADCAST_MODE_UNSPECIFIED")]
    Unspecified,
    #[serde(rename = "BROADCAST_MODE_BLOCK")]
    Block,
    #[serde(rename = "BROADCAST_MODE_SYNC")]
    Sync,
    #[serde(rename = "BROADCAST_MODE_ASYNC")]
    Async,
}

impl ToString for CosmosTxV1beta1BroadcastMode {
    fn to_string(&self) -> String {
        match self {
            Self::Unspecified => String::from("BROADCAST_MODE_UNSPECIFIED"),
            Self::Block => String::from("BROADCAST_MODE_BLOCK"),
            Self::Sync => String::from("BROADCAST_MODE_SYNC"),
            Self::Async => String::from("BROADCAST_MODE_ASYNC"),
        }
    }
}

impl Default for CosmosTxV1beta1BroadcastMode {
    fn default() -> CosmosTxV1beta1BroadcastMode {
        Self::Unspecified
    }
}
