/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

/// CosmosStakingV1beta1UnbondingDelegation : UnbondingDelegation stores all of a single delegator's unbonding bonds for a single validator in an time-ordered list.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosStakingV1beta1UnbondingDelegation {
    /// delegator_address is the bech32-encoded address of the delegator.
    #[serde(rename = "delegator_address", skip_serializing_if = "Option::is_none")]
    pub delegator_address: Option<String>,
    /// validator_address is the bech32-encoded address of the validator.
    #[serde(rename = "validator_address", skip_serializing_if = "Option::is_none")]
    pub validator_address: Option<String>,
    /// entries are the unbonding delegation entries.
    #[serde(rename = "entries", skip_serializing_if = "Option::is_none")]
    pub entries: Option<
        Vec<
            crate::models::DelegatorUnbondingDelegationsResponseUnbondingResponsesInnerEntriesInner,
        >,
    >,
}

impl CosmosStakingV1beta1UnbondingDelegation {
    /// UnbondingDelegation stores all of a single delegator's unbonding bonds for a single validator in an time-ordered list.
    pub fn new() -> CosmosStakingV1beta1UnbondingDelegation {
        CosmosStakingV1beta1UnbondingDelegation {
            delegator_address: None,
            validator_address: None,
            entries: None,
        }
    }
}
