/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

/// CosmosGovV1beta1QueryVoteResponse : QueryVoteResponse is the response type for the Query/Vote RPC method.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosGovV1beta1QueryVoteResponse {
    #[serde(rename = "vote", skip_serializing_if = "Option::is_none")]
    pub vote: Option<Box<crate::models::VotesResponseVotesInner>>,
}

impl CosmosGovV1beta1QueryVoteResponse {
    /// QueryVoteResponse is the response type for the Query/Vote RPC method.
    pub fn new() -> CosmosGovV1beta1QueryVoteResponse {
        CosmosGovV1beta1QueryVoteResponse { vote: None }
    }
}
