/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

/// CosmosDistributionV1beta1QueryValidatorOutstandingRewardsResponse : QueryValidatorOutstandingRewardsResponse is the response type for the Query/ValidatorOutstandingRewards RPC method.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosDistributionV1beta1QueryValidatorOutstandingRewardsResponse {
    #[serde(rename = "rewards", skip_serializing_if = "Option::is_none")]
    pub rewards: Option<Box<crate::models::ValidatorOutstandingRewardsResponseRewards>>,
}

impl CosmosDistributionV1beta1QueryValidatorOutstandingRewardsResponse {
    /// QueryValidatorOutstandingRewardsResponse is the response type for the Query/ValidatorOutstandingRewards RPC method.
    pub fn new() -> CosmosDistributionV1beta1QueryValidatorOutstandingRewardsResponse {
        CosmosDistributionV1beta1QueryValidatorOutstandingRewardsResponse { rewards: None }
    }
}
