/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

/// CosmosTxV1beta1OrderBy : - ORDER_BY_UNSPECIFIED: ORDER_BY_UNSPECIFIED specifies an unknown sorting order. OrderBy defaults to ASC in this case.  - ORDER_BY_ASC: ORDER_BY_ASC defines ascending order  - ORDER_BY_DESC: ORDER_BY_DESC defines descending order

/// - ORDER_BY_UNSPECIFIED: ORDER_BY_UNSPECIFIED specifies an unknown sorting order. OrderBy defaults to ASC in this case.  - ORDER_BY_ASC: ORDER_BY_ASC defines ascending order  - ORDER_BY_DESC: ORDER_BY_DESC defines descending order
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CosmosTxV1beta1OrderBy {
    #[serde(rename = "ORDER_BY_UNSPECIFIED")]
    Unspecified,
    #[serde(rename = "ORDER_BY_ASC")]
    Asc,
    #[serde(rename = "ORDER_BY_DESC")]
    Desc,
}

impl ToString for CosmosTxV1beta1OrderBy {
    fn to_string(&self) -> String {
        match self {
            Self::Unspecified => String::from("ORDER_BY_UNSPECIFIED"),
            Self::Asc => String::from("ORDER_BY_ASC"),
            Self::Desc => String::from("ORDER_BY_DESC"),
        }
    }
}

impl Default for CosmosTxV1beta1OrderBy {
    fn default() -> CosmosTxV1beta1OrderBy {
        Self::Unspecified
    }
}
