/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

/// CosmosSlashingV1beta1Params : Params represents the parameters used for by the slashing module.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosSlashingV1beta1Params {
    #[serde(
        rename = "signed_blocks_window",
        skip_serializing_if = "Option::is_none"
    )]
    pub signed_blocks_window: Option<String>,
    #[serde(
        rename = "min_signed_per_window",
        skip_serializing_if = "Option::is_none"
    )]
    pub min_signed_per_window: Option<String>,
    #[serde(
        rename = "downtime_jail_duration",
        skip_serializing_if = "Option::is_none"
    )]
    pub downtime_jail_duration: Option<String>,
    #[serde(
        rename = "slash_fraction_double_sign",
        skip_serializing_if = "Option::is_none"
    )]
    pub slash_fraction_double_sign: Option<String>,
    #[serde(
        rename = "slash_fraction_downtime",
        skip_serializing_if = "Option::is_none"
    )]
    pub slash_fraction_downtime: Option<String>,
}

impl CosmosSlashingV1beta1Params {
    /// Params represents the parameters used for by the slashing module.
    pub fn new() -> CosmosSlashingV1beta1Params {
        CosmosSlashingV1beta1Params {
            signed_blocks_window: None,
            min_signed_per_window: None,
            downtime_jail_duration: None,
            slash_fraction_double_sign: None,
            slash_fraction_downtime: None,
        }
    }
}
