/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

/// CosmosStakingV1beta1QueryDelegatorValidatorsResponse : QueryDelegatorValidatorsResponse is response type for the Query/DelegatorValidators RPC method.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosStakingV1beta1QueryDelegatorValidatorsResponse {
    /// validators defines the the validators' info of a delegator.
    #[serde(rename = "validators", skip_serializing_if = "Option::is_none")]
    pub validators: Option<Vec<crate::models::DelegatorValidatorsInfoResponseValidatorsInner>>,
    #[serde(rename = "pagination", skip_serializing_if = "Option::is_none")]
    pub pagination: Option<Box<crate::models::AccountsResponsePagination>>,
}

impl CosmosStakingV1beta1QueryDelegatorValidatorsResponse {
    /// QueryDelegatorValidatorsResponse is response type for the Query/DelegatorValidators RPC method.
    pub fn new() -> CosmosStakingV1beta1QueryDelegatorValidatorsResponse {
        CosmosStakingV1beta1QueryDelegatorValidatorsResponse {
            validators: None,
            pagination: None,
        }
    }
}
