/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

/// CosmosStakingV1beta1QueryDelegatorValidatorResponse : QueryDelegatorValidatorResponse response type for the Query/DelegatorValidator RPC method.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosStakingV1beta1QueryDelegatorValidatorResponse {
    #[serde(rename = "validator", skip_serializing_if = "Option::is_none")]
    pub validator: Option<Box<crate::models::DelegatorValidatorsInfoResponseValidatorsInner>>,
}

impl CosmosStakingV1beta1QueryDelegatorValidatorResponse {
    /// QueryDelegatorValidatorResponse response type for the Query/DelegatorValidator RPC method.
    pub fn new() -> CosmosStakingV1beta1QueryDelegatorValidatorResponse {
        CosmosStakingV1beta1QueryDelegatorValidatorResponse { validator: None }
    }
}
