/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

/// CosmosStakingV1beta1Description : Description defines a validator description.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosStakingV1beta1Description {
    /// moniker defines a human-readable name for the validator.
    #[serde(rename = "moniker", skip_serializing_if = "Option::is_none")]
    pub moniker: Option<String>,
    /// identity defines an optional identity signature (ex. UPort or Keybase).
    #[serde(rename = "identity", skip_serializing_if = "Option::is_none")]
    pub identity: Option<String>,
    /// website defines an optional website link.
    #[serde(rename = "website", skip_serializing_if = "Option::is_none")]
    pub website: Option<String>,
    /// security_contact defines an optional email for security contact.
    #[serde(rename = "security_contact", skip_serializing_if = "Option::is_none")]
    pub security_contact: Option<String>,
    /// details define other optional details.
    #[serde(rename = "details", skip_serializing_if = "Option::is_none")]
    pub details: Option<String>,
}

impl CosmosStakingV1beta1Description {
    /// Description defines a validator description.
    pub fn new() -> CosmosStakingV1beta1Description {
        CosmosStakingV1beta1Description {
            moniker: None,
            identity: None,
            website: None,
            security_contact: None,
            details: None,
        }
    }
}
