/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

/// CosmosStakingV1beta1QueryUnbondingDelegationResponse : QueryDelegationResponse is response type for the Query/UnbondingDelegation RPC method.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosStakingV1beta1QueryUnbondingDelegationResponse {
    #[serde(rename = "unbond", skip_serializing_if = "Option::is_none")]
    pub unbond:
        Option<Box<crate::models::DelegatorUnbondingDelegationsResponseUnbondingResponsesInner>>,
}

impl CosmosStakingV1beta1QueryUnbondingDelegationResponse {
    /// QueryDelegationResponse is response type for the Query/UnbondingDelegation RPC method.
    pub fn new() -> CosmosStakingV1beta1QueryUnbondingDelegationResponse {
        CosmosStakingV1beta1QueryUnbondingDelegationResponse { unbond: None }
    }
}
