/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosStakingV1beta1QueryValidatorsResponse {
    /// validators contains all the queried validators.
    #[serde(rename = "validators", skip_serializing_if = "Option::is_none")]
    pub validators: Option<Vec<crate::models::DelegatorValidatorsInfoResponseValidatorsInner>>,
    #[serde(rename = "pagination", skip_serializing_if = "Option::is_none")]
    pub pagination: Option<Box<crate::models::AccountsResponsePagination>>,
}

impl CosmosStakingV1beta1QueryValidatorsResponse {
    pub fn new() -> CosmosStakingV1beta1QueryValidatorsResponse {
        CosmosStakingV1beta1QueryValidatorsResponse {
            validators: None,
            pagination: None,
        }
    }
}
