/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

/// CosmosTxV1beta1SimulateResponse : SimulateResponse is the response type for the Service.SimulateRPC method.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosTxV1beta1SimulateResponse {
    #[serde(rename = "gas_info", skip_serializing_if = "Option::is_none")]
    pub gas_info: Option<Box<crate::models::SimulateResponseGasInfo>>,
    #[serde(rename = "result", skip_serializing_if = "Option::is_none")]
    pub result: Option<Box<crate::models::SimulateResponseResult>>,
}

impl CosmosTxV1beta1SimulateResponse {
    /// SimulateResponse is the response type for the Service.SimulateRPC method.
    pub fn new() -> CosmosTxV1beta1SimulateResponse {
        CosmosTxV1beta1SimulateResponse {
            gas_info: None,
            result: None,
        }
    }
}
