/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

/// CosmosMintV1beta1QueryInflationResponse : QueryInflationResponse is the response type for the Query/Inflation RPC method.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosMintV1beta1QueryInflationResponse {
    /// inflation is the current minting inflation value.
    #[serde(rename = "inflation", skip_serializing_if = "Option::is_none")]
    pub inflation: Option<String>,
}

impl CosmosMintV1beta1QueryInflationResponse {
    /// QueryInflationResponse is the response type for the Query/Inflation RPC method.
    pub fn new() -> CosmosMintV1beta1QueryInflationResponse {
        CosmosMintV1beta1QueryInflationResponse { inflation: None }
    }
}
