/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

/// CosmosBankV1beta1QueryAllBalancesResponse : QueryAllBalancesResponse is the response type for the Query/AllBalances RPC method.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosBankV1beta1QueryAllBalancesResponse {
    /// balances is the balances of all the coins.
    #[serde(rename = "balances", skip_serializing_if = "Option::is_none")]
    pub balances: Option<Vec<crate::models::AllBalancesResponseBalancesInner>>,
    #[serde(rename = "pagination", skip_serializing_if = "Option::is_none")]
    pub pagination: Option<Box<crate::models::AccountsResponsePagination>>,
}

impl CosmosBankV1beta1QueryAllBalancesResponse {
    /// QueryAllBalancesResponse is the response type for the Query/AllBalances RPC method.
    pub fn new() -> CosmosBankV1beta1QueryAllBalancesResponse {
        CosmosBankV1beta1QueryAllBalancesResponse {
            balances: None,
            pagination: None,
        }
    }
}
