/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

/// CosmosCryptoMultisigV1beta1CompactBitArray : CompactBitArray is an implementation of a space efficient bit array. This is used to ensure that the encoded data takes up a minimal amount of space after proto encoding. This is not thread safe, and is not intended for concurrent usage.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosCryptoMultisigV1beta1CompactBitArray {
    #[serde(rename = "extra_bits_stored", skip_serializing_if = "Option::is_none")]
    pub extra_bits_stored: Option<i64>,
    #[serde(rename = "elems", skip_serializing_if = "Option::is_none")]
    pub elems: Option<String>,
}

impl CosmosCryptoMultisigV1beta1CompactBitArray {
    /// CompactBitArray is an implementation of a space efficient bit array. This is used to ensure that the encoded data takes up a minimal amount of space after proto encoding. This is not thread safe, and is not intended for concurrent usage.
    pub fn new() -> CosmosCryptoMultisigV1beta1CompactBitArray {
        CosmosCryptoMultisigV1beta1CompactBitArray {
            extra_bits_stored: None,
            elems: None,
        }
    }
}
