/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

/// CosmosStakingV1beta1RedelegationEntryResponse : RedelegationEntryResponse is equivalent to a RedelegationEntry except that it contains a balance in addition to shares which is more suitable for client responses.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosStakingV1beta1RedelegationEntryResponse {
    #[serde(rename = "redelegation_entry", skip_serializing_if = "Option::is_none")]
    pub redelegation_entry: Option<
        Box<crate::models::RedelegationsResponseRedelegationResponsesInnerRedelegationEntriesInner>,
    >,
    #[serde(rename = "balance", skip_serializing_if = "Option::is_none")]
    pub balance: Option<String>,
}

impl CosmosStakingV1beta1RedelegationEntryResponse {
    /// RedelegationEntryResponse is equivalent to a RedelegationEntry except that it contains a balance in addition to shares which is more suitable for client responses.
    pub fn new() -> CosmosStakingV1beta1RedelegationEntryResponse {
        CosmosStakingV1beta1RedelegationEntryResponse {
            redelegation_entry: None,
            balance: None,
        }
    }
}
