/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

/// CosmosParamsV1beta1QueryParamsResponse : QueryParamsResponse is response type for the Query/Params RPC method.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosParamsV1beta1QueryParamsResponse {
    #[serde(rename = "param", skip_serializing_if = "Option::is_none")]
    pub param: Option<Box<crate::models::ParamsResponseParam>>,
}

impl CosmosParamsV1beta1QueryParamsResponse {
    /// QueryParamsResponse is response type for the Query/Params RPC method.
    pub fn new() -> CosmosParamsV1beta1QueryParamsResponse {
        CosmosParamsV1beta1QueryParamsResponse { param: None }
    }
}
