/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

/// CosmosGovV1beta1QueryProposalResponse : QueryProposalResponse is the response type for the Query/Proposal RPC method.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosGovV1beta1QueryProposalResponse {
    #[serde(rename = "proposal", skip_serializing_if = "Option::is_none")]
    pub proposal: Option<Box<crate::models::ProposalsResponseProposalsInner>>,
}

impl CosmosGovV1beta1QueryProposalResponse {
    /// QueryProposalResponse is the response type for the Query/Proposal RPC method.
    pub fn new() -> CosmosGovV1beta1QueryProposalResponse {
        CosmosGovV1beta1QueryProposalResponse { proposal: None }
    }
}
