/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

/// CosmosDistributionV1beta1QueryDelegationTotalRewardsResponse : QueryDelegationTotalRewardsResponse is the response type for the Query/DelegationTotalRewards RPC method.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosDistributionV1beta1QueryDelegationTotalRewardsResponse {
    /// rewards defines all the rewards accrued by a delegator.
    #[serde(rename = "rewards", skip_serializing_if = "Option::is_none")]
    pub rewards: Option<Vec<crate::models::DelegationTotalRewardsResponseRewardsInner>>,
    /// total defines the sum of all the rewards.
    #[serde(rename = "total", skip_serializing_if = "Option::is_none")]
    pub total: Option<Vec<crate::models::CommunityPoolResponsePoolInner>>,
}

impl CosmosDistributionV1beta1QueryDelegationTotalRewardsResponse {
    /// QueryDelegationTotalRewardsResponse is the response type for the Query/DelegationTotalRewards RPC method.
    pub fn new() -> CosmosDistributionV1beta1QueryDelegationTotalRewardsResponse {
        CosmosDistributionV1beta1QueryDelegationTotalRewardsResponse {
            rewards: None,
            total: None,
        }
    }
}
