/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

/// CosmosFeegrantV1beta1QueryAllowancesResponse : QueryAllowancesResponse is the response type for the Query/Allowances RPC method.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosFeegrantV1beta1QueryAllowancesResponse {
    /// allowances are allowance's granted for grantee by granter.
    #[serde(rename = "allowances", skip_serializing_if = "Option::is_none")]
    pub allowances:
        Option<Vec<crate::models::GrantIsStoredInTheKvStoreToRecordAGrantWithFullContext1>>,
    #[serde(rename = "pagination", skip_serializing_if = "Option::is_none")]
    pub pagination: Option<Box<crate::models::GrantsResponsePagination>>,
}

impl CosmosFeegrantV1beta1QueryAllowancesResponse {
    /// QueryAllowancesResponse is the response type for the Query/Allowances RPC method.
    pub fn new() -> CosmosFeegrantV1beta1QueryAllowancesResponse {
        CosmosFeegrantV1beta1QueryAllowancesResponse {
            allowances: None,
            pagination: None,
        }
    }
}
