/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

/// CosmosBankV1beta1QueryDenomMetadataResponse : QueryDenomMetadataResponse is the response type for the Query/DenomMetadata RPC method.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosBankV1beta1QueryDenomMetadataResponse {
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<Box<crate::models::DenomsMetadataResponseMetadatasInner>>,
}

impl CosmosBankV1beta1QueryDenomMetadataResponse {
    /// QueryDenomMetadataResponse is the response type for the Query/DenomMetadata RPC method.
    pub fn new() -> CosmosBankV1beta1QueryDenomMetadataResponse {
        CosmosBankV1beta1QueryDenomMetadataResponse { metadata: None }
    }
}
