/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

/// CosmosTxV1beta1GetTxsEventResponse : GetTxsEventResponse is the response type for the Service.TxsByEvents RPC method.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosTxV1beta1GetTxsEventResponse {
    /// txs is the list of queried transactions.
    #[serde(rename = "txs", skip_serializing_if = "Option::is_none")]
    pub txs: Option<Vec<crate::models::GetTxsEventResponseTxsInner>>,
    /// tx_responses is the list of queried TxResponses.
    #[serde(rename = "tx_responses", skip_serializing_if = "Option::is_none")]
    pub tx_responses: Option<Vec<crate::models::GetTxsEventResponseTxResponsesInner>>,
    #[serde(rename = "pagination", skip_serializing_if = "Option::is_none")]
    pub pagination: Option<Box<crate::models::GetTxsEventResponsePagination>>,
}

impl CosmosTxV1beta1GetTxsEventResponse {
    /// GetTxsEventResponse is the response type for the Service.TxsByEvents RPC method.
    pub fn new() -> CosmosTxV1beta1GetTxsEventResponse {
        CosmosTxV1beta1GetTxsEventResponse {
            txs: None,
            tx_responses: None,
            pagination: None,
        }
    }
}
