/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

/// CosmosUpgradeV1beta1QueryUpgradedConsensusStateResponse : QueryUpgradedConsensusStateResponse is the response type for the Query/UpgradedConsensusState RPC method.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosUpgradeV1beta1QueryUpgradedConsensusStateResponse {
    #[serde(
        rename = "upgraded_consensus_state",
        skip_serializing_if = "Option::is_none"
    )]
    pub upgraded_consensus_state: Option<String>,
}

impl CosmosUpgradeV1beta1QueryUpgradedConsensusStateResponse {
    /// QueryUpgradedConsensusStateResponse is the response type for the Query/UpgradedConsensusState RPC method.
    pub fn new() -> CosmosUpgradeV1beta1QueryUpgradedConsensusStateResponse {
        CosmosUpgradeV1beta1QueryUpgradedConsensusStateResponse {
            upgraded_consensus_state: None,
        }
    }
}
