/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

/// CosmosStakingV1beta1Delegation : Delegation represents the bond with tokens held by an account. It is owned by one delegator, and is associated with the voting power of one validator.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosStakingV1beta1Delegation {
    /// delegator_address is the bech32-encoded address of the delegator.
    #[serde(rename = "delegator_address", skip_serializing_if = "Option::is_none")]
    pub delegator_address: Option<String>,
    /// validator_address is the bech32-encoded address of the validator.
    #[serde(rename = "validator_address", skip_serializing_if = "Option::is_none")]
    pub validator_address: Option<String>,
    /// shares define the delegation shares received.
    #[serde(rename = "shares", skip_serializing_if = "Option::is_none")]
    pub shares: Option<String>,
}

impl CosmosStakingV1beta1Delegation {
    /// Delegation represents the bond with tokens held by an account. It is owned by one delegator, and is associated with the voting power of one validator.
    pub fn new() -> CosmosStakingV1beta1Delegation {
        CosmosStakingV1beta1Delegation {
            delegator_address: None,
            validator_address: None,
            shares: None,
        }
    }
}
