/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosSlashingV1beta1QuerySigningInfosResponse {
    #[serde(rename = "info", skip_serializing_if = "Option::is_none")]
    pub info: Option<Vec<crate::models::InfoIsTheSigningInfoOfAllValidatorsInner>>,
    #[serde(rename = "pagination", skip_serializing_if = "Option::is_none")]
    pub pagination: Option<Box<crate::models::QuerySigningInfosResponseIsTheResponseTypeForTheQuerySigningInfosRpcMethodPagination>>,
}

impl CosmosSlashingV1beta1QuerySigningInfosResponse {
    pub fn new() -> CosmosSlashingV1beta1QuerySigningInfosResponse {
        CosmosSlashingV1beta1QuerySigningInfosResponse {
            info: None,
            pagination: None,
        }
    }
}
