/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

/// CosmosDistributionV1beta1DelegationDelegatorReward : DelegationDelegatorReward represents the properties of a delegator's delegation reward.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosDistributionV1beta1DelegationDelegatorReward {
    #[serde(rename = "validator_address", skip_serializing_if = "Option::is_none")]
    pub validator_address: Option<String>,
    #[serde(rename = "reward", skip_serializing_if = "Option::is_none")]
    pub reward: Option<Vec<crate::models::CommunityPoolResponsePoolInner>>,
}

impl CosmosDistributionV1beta1DelegationDelegatorReward {
    /// DelegationDelegatorReward represents the properties of a delegator's delegation reward.
    pub fn new() -> CosmosDistributionV1beta1DelegationDelegatorReward {
        CosmosDistributionV1beta1DelegationDelegatorReward {
            validator_address: None,
            reward: None,
        }
    }
}
