/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

/// CosmosBankV1beta1Params : Params defines the parameters for the bank module.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosBankV1beta1Params {
    #[serde(rename = "send_enabled", skip_serializing_if = "Option::is_none")]
    pub send_enabled: Option<Vec<crate::models::BankParamsResponseParamsSendEnabledInner>>,
    #[serde(
        rename = "default_send_enabled",
        skip_serializing_if = "Option::is_none"
    )]
    pub default_send_enabled: Option<bool>,
}

impl CosmosBankV1beta1Params {
    /// Params defines the parameters for the bank module.
    pub fn new() -> CosmosBankV1beta1Params {
        CosmosBankV1beta1Params {
            send_enabled: None,
            default_send_enabled: None,
        }
    }
}
