/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

/// CosmosBankV1beta1QueryParamsResponse : QueryParamsResponse defines the response type for querying x/bank parameters.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosBankV1beta1QueryParamsResponse {
    #[serde(rename = "params", skip_serializing_if = "Option::is_none")]
    pub params: Option<Box<crate::models::BankParamsResponseParams>>,
}

impl CosmosBankV1beta1QueryParamsResponse {
    /// QueryParamsResponse defines the response type for querying x/bank parameters.
    pub fn new() -> CosmosBankV1beta1QueryParamsResponse {
        CosmosBankV1beta1QueryParamsResponse { params: None }
    }
}
