/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

/// CosmosGovV1beta1Deposit : Deposit defines an amount deposited by an account address to an active proposal.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosGovV1beta1Deposit {
    #[serde(rename = "proposal_id", skip_serializing_if = "Option::is_none")]
    pub proposal_id: Option<String>,
    #[serde(rename = "depositor", skip_serializing_if = "Option::is_none")]
    pub depositor: Option<String>,
    #[serde(rename = "amount", skip_serializing_if = "Option::is_none")]
    pub amount: Option<Vec<crate::models::AllBalancesResponseBalancesInner>>,
}

impl CosmosGovV1beta1Deposit {
    /// Deposit defines an amount deposited by an account address to an active proposal.
    pub fn new() -> CosmosGovV1beta1Deposit {
        CosmosGovV1beta1Deposit {
            proposal_id: None,
            depositor: None,
            amount: None,
        }
    }
}
