/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

/// CosmosStakingV1beta1QueryDelegatorUnbondingDelegationsResponse : QueryUnbondingDelegatorDelegationsResponse is response type for the Query/UnbondingDelegatorDelegations RPC method.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosStakingV1beta1QueryDelegatorUnbondingDelegationsResponse {
    #[serde(
        rename = "unbonding_responses",
        skip_serializing_if = "Option::is_none"
    )]
    pub unbonding_responses:
        Option<Vec<crate::models::DelegatorUnbondingDelegationsResponseUnbondingResponsesInner>>,
    #[serde(rename = "pagination", skip_serializing_if = "Option::is_none")]
    pub pagination: Option<Box<crate::models::AccountsResponsePagination>>,
}

impl CosmosStakingV1beta1QueryDelegatorUnbondingDelegationsResponse {
    /// QueryUnbondingDelegatorDelegationsResponse is response type for the Query/UnbondingDelegatorDelegations RPC method.
    pub fn new() -> CosmosStakingV1beta1QueryDelegatorUnbondingDelegationsResponse {
        CosmosStakingV1beta1QueryDelegatorUnbondingDelegationsResponse {
            unbonding_responses: None,
            pagination: None,
        }
    }
}
