/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

/// CosmosDistributionV1beta1QueryDelegationRewardsResponse : QueryDelegationRewardsResponse is the response type for the Query/DelegationRewards RPC method.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosDistributionV1beta1QueryDelegationRewardsResponse {
    /// rewards defines the rewards accrued by a delegation.
    #[serde(rename = "rewards", skip_serializing_if = "Option::is_none")]
    pub rewards: Option<Vec<crate::models::CommunityPoolResponsePoolInner>>,
}

impl CosmosDistributionV1beta1QueryDelegationRewardsResponse {
    /// QueryDelegationRewardsResponse is the response type for the Query/DelegationRewards RPC method.
    pub fn new() -> CosmosDistributionV1beta1QueryDelegationRewardsResponse {
        CosmosDistributionV1beta1QueryDelegationRewardsResponse { rewards: None }
    }
}
