/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

/// CosmosGovV1beta1VotingParams : VotingParams defines the params for voting on governance proposals.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosGovV1beta1VotingParams {
    /// Length of the voting period.
    #[serde(rename = "voting_period", skip_serializing_if = "Option::is_none")]
    pub voting_period: Option<String>,
    /// Length of the expedited voting period.
    #[serde(
        rename = "expedited_voting_period",
        skip_serializing_if = "Option::is_none"
    )]
    pub expedited_voting_period: Option<String>,
}

impl CosmosGovV1beta1VotingParams {
    /// VotingParams defines the params for voting on governance proposals.
    pub fn new() -> CosmosGovV1beta1VotingParams {
        CosmosGovV1beta1VotingParams {
            voting_period: None,
            expedited_voting_period: None,
        }
    }
}
