/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

/// CosmosBaseTendermintV1beta1GetSyncingResponse : GetSyncingResponse is the response type for the Query/GetSyncing RPC method.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosBaseTendermintV1beta1GetSyncingResponse {
    #[serde(rename = "syncing", skip_serializing_if = "Option::is_none")]
    pub syncing: Option<bool>,
}

impl CosmosBaseTendermintV1beta1GetSyncingResponse {
    /// GetSyncingResponse is the response type for the Query/GetSyncing RPC method.
    pub fn new() -> CosmosBaseTendermintV1beta1GetSyncingResponse {
        CosmosBaseTendermintV1beta1GetSyncingResponse { syncing: None }
    }
}
