/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

/// CosmosBankV1beta1QueryBalanceResponse : QueryBalanceResponse is the response type for the Query/Balance RPC method.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosBankV1beta1QueryBalanceResponse {
    #[serde(rename = "balance", skip_serializing_if = "Option::is_none")]
    pub balance: Option<Box<crate::models::AllBalancesResponseBalancesInner>>,
}

impl CosmosBankV1beta1QueryBalanceResponse {
    /// QueryBalanceResponse is the response type for the Query/Balance RPC method.
    pub fn new() -> CosmosBankV1beta1QueryBalanceResponse {
        CosmosBankV1beta1QueryBalanceResponse { balance: None }
    }
}
