/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CosmosBankV1beta1QueryTotalSupplyResponse {
    #[serde(rename = "supply", skip_serializing_if = "Option::is_none")]
    pub supply: Option<Vec<crate::models::AllBalancesResponseBalancesInner>>,
    #[serde(rename = "pagination", skip_serializing_if = "Option::is_none")]
    pub pagination: Option<Box<crate::models::QueryTotalSupplyResponseIsTheResponseTypeForTheQueryTotalSupplyRpcMethodPagination>>,
}

impl CosmosBankV1beta1QueryTotalSupplyResponse {
    pub fn new() -> CosmosBankV1beta1QueryTotalSupplyResponse {
        CosmosBankV1beta1QueryTotalSupplyResponse {
            supply: None,
            pagination: None,
        }
    }
}
