/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

/// CurrentPlanResponse : QueryCurrentPlanResponse is the response type for the Query/CurrentPlan RPC method.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CurrentPlanResponse {
    #[serde(rename = "plan", skip_serializing_if = "Option::is_none")]
    pub plan: Option<Box<crate::models::CurrentPlanResponsePlan>>,
}

impl CurrentPlanResponse {
    /// QueryCurrentPlanResponse is the response type for the Query/CurrentPlan RPC method.
    pub fn new() -> CurrentPlanResponse {
        CurrentPlanResponse { plan: None }
    }
}
