/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Delegation {
    #[serde(rename = "delegator_address", skip_serializing_if = "Option::is_none")]
    pub delegator_address: Option<String>,
    #[serde(rename = "validator_address", skip_serializing_if = "Option::is_none")]
    pub validator_address: Option<String>,
    #[serde(rename = "shares", skip_serializing_if = "Option::is_none")]
    pub shares: Option<String>,
    #[serde(rename = "balance", skip_serializing_if = "Option::is_none")]
    pub balance: Option<Box<crate::models::TxsHashGetResponseTxFeeAmountInner>>,
}

impl Delegation {
    pub fn new() -> Delegation {
        Delegation {
            delegator_address: None,
            validator_address: None,
            shares: None,
            balance: None,
        }
    }
}
