/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DelegationDelegatorReward {
    /// bech32 encoded address
    #[serde(rename = "validator_address", skip_serializing_if = "Option::is_none")]
    pub validator_address: Option<String>,
    #[serde(rename = "reward", skip_serializing_if = "Option::is_none")]
    pub reward: Option<Vec<crate::models::TxsHashGetResponseTxFeeAmountInner>>,
}

impl DelegationDelegatorReward {
    pub fn new() -> DelegationDelegatorReward {
        DelegationDelegatorReward {
            validator_address: None,
            reward: None,
        }
    }
}
