/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

/// DelegatorValidatorsResponse : QueryDelegatorValidatorsResponse is the response type for the Query/DelegatorValidators RPC method.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DelegatorValidatorsResponse {
    /// validators defines the validators a delegator is delegating for.
    #[serde(rename = "validators", skip_serializing_if = "Option::is_none")]
    pub validators: Option<Vec<String>>,
}

impl DelegatorValidatorsResponse {
    /// QueryDelegatorValidatorsResponse is the response type for the Query/DelegatorValidators RPC method.
    pub fn new() -> DelegatorValidatorsResponse {
        DelegatorValidatorsResponse { validators: None }
    }
}
