/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

/// DelegatorWithdrawAddressResponse : QueryDelegatorWithdrawAddressResponse is the response type for the Query/DelegatorWithdrawAddress RPC method.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DelegatorWithdrawAddressResponse {
    /// withdraw_address defines the delegator address to query for.
    #[serde(rename = "withdraw_address", skip_serializing_if = "Option::is_none")]
    pub withdraw_address: Option<String>,
}

impl DelegatorWithdrawAddressResponse {
    /// QueryDelegatorWithdrawAddressResponse is the response type for the Query/DelegatorWithdrawAddress RPC method.
    pub fn new() -> DelegatorWithdrawAddressResponse {
        DelegatorWithdrawAddressResponse {
            withdraw_address: None,
        }
    }
}
