/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

/// DelegatorValidatorsInfoResponseValidatorsInner : Validator defines a validator, together with the total amount of the Validator's bond shares and their exchange rate to coins. Slashing results in a decrease in the exchange rate, allowing correct calculation of future undelegations without iterating over delegators. When coins are delegated to this validator, the validator is credited with a delegation whose number of bond shares is based on the amount of coins delegated divided by the current exchange rate. Voting power can be calculated as total bonded shares multiplied by exchange rate.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DelegatorValidatorsInfoResponseValidatorsInner {
    /// operator_address defines the address of the validator's operator; bech encoded in JSON.
    #[serde(rename = "operator_address", skip_serializing_if = "Option::is_none")]
    pub operator_address: Option<String>,
    #[serde(rename = "consensus_pubkey", skip_serializing_if = "Option::is_none")]
    pub consensus_pubkey: Option<Box<crate::models::AccountsAreTheExistingAccountsInner>>,
    /// jailed defined whether the validator has been jailed from bonded status or not.
    #[serde(rename = "jailed", skip_serializing_if = "Option::is_none")]
    pub jailed: Option<bool>,
    /// status is the validator status (bonded/unbonding/unbonded).
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<Status>,
    /// tokens define the delegated tokens (incl. self-delegation).
    #[serde(rename = "tokens", skip_serializing_if = "Option::is_none")]
    pub tokens: Option<String>,
    /// delegator_shares defines total shares issued to a validator's delegators.
    #[serde(rename = "delegator_shares", skip_serializing_if = "Option::is_none")]
    pub delegator_shares: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description:
        Option<Box<crate::models::DelegatorValidatorsInfoResponseValidatorsInnerDescription>>,
    /// unbonding_height defines, if unbonding, the height at which this validator has begun unbonding.
    #[serde(rename = "unbonding_height", skip_serializing_if = "Option::is_none")]
    pub unbonding_height: Option<String>,
    /// unbonding_time defines, if unbonding, the min time for the validator to complete unbonding.
    #[serde(rename = "unbonding_time", skip_serializing_if = "Option::is_none")]
    pub unbonding_time: Option<String>,
    #[serde(rename = "commission", skip_serializing_if = "Option::is_none")]
    pub commission:
        Option<Box<crate::models::DelegatorValidatorsInfoResponseValidatorsInnerCommission>>,
    /// min_self_delegation is the validator's self declared minimum self delegation.
    #[serde(
        rename = "min_self_delegation",
        skip_serializing_if = "Option::is_none"
    )]
    pub min_self_delegation: Option<String>,
}

impl DelegatorValidatorsInfoResponseValidatorsInner {
    /// Validator defines a validator, together with the total amount of the Validator's bond shares and their exchange rate to coins. Slashing results in a decrease in the exchange rate, allowing correct calculation of future undelegations without iterating over delegators. When coins are delegated to this validator, the validator is credited with a delegation whose number of bond shares is based on the amount of coins delegated divided by the current exchange rate. Voting power can be calculated as total bonded shares multiplied by exchange rate.
    pub fn new() -> DelegatorValidatorsInfoResponseValidatorsInner {
        DelegatorValidatorsInfoResponseValidatorsInner {
            operator_address: None,
            consensus_pubkey: None,
            jailed: None,
            status: None,
            tokens: None,
            delegator_shares: None,
            description: None,
            unbonding_height: None,
            unbonding_time: None,
            commission: None,
            min_self_delegation: None,
        }
    }
}

/// status is the validator status (bonded/unbonding/unbonded).
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "BOND_STATUS_UNSPECIFIED")]
    Unspecified,
    #[serde(rename = "BOND_STATUS_UNBONDED")]
    Unbonded,
    #[serde(rename = "BOND_STATUS_UNBONDING")]
    Unbonding,
    #[serde(rename = "BOND_STATUS_BONDED")]
    Bonded,
}

impl Default for Status {
    fn default() -> Status {
        Self::Unspecified
    }
}
