/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

/// DelegatorUnbondingDelegationsResponseUnbondingResponsesInnerEntriesInner : UnbondingDelegationEntry defines an unbonding object with relevant metadata.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DelegatorUnbondingDelegationsResponseUnbondingResponsesInnerEntriesInner {
    /// creation_height is the height which the unbonding took place.
    #[serde(rename = "creation_height", skip_serializing_if = "Option::is_none")]
    pub creation_height: Option<String>,
    /// completion_time is the unix time for unbonding completion.
    #[serde(rename = "completion_time", skip_serializing_if = "Option::is_none")]
    pub completion_time: Option<String>,
    /// initial_balance defines the tokens initially scheduled to receive at completion.
    #[serde(rename = "initial_balance", skip_serializing_if = "Option::is_none")]
    pub initial_balance: Option<String>,
    /// balance defines the tokens to receive at completion.
    #[serde(rename = "balance", skip_serializing_if = "Option::is_none")]
    pub balance: Option<String>,
}

impl DelegatorUnbondingDelegationsResponseUnbondingResponsesInnerEntriesInner {
    /// UnbondingDelegationEntry defines an unbonding object with relevant metadata.
    pub fn new() -> DelegatorUnbondingDelegationsResponseUnbondingResponsesInnerEntriesInner {
        DelegatorUnbondingDelegationsResponseUnbondingResponsesInnerEntriesInner {
            creation_height: None,
            completion_time: None,
            initial_balance: None,
            balance: None,
        }
    }
}
