/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

/// DenomHashResponse : QueryDenomHashResponse is the response type for the Query/DenomHash RPC method.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DenomHashResponse {
    /// hash (in hex format) of the denomination trace information.
    #[serde(rename = "hash", skip_serializing_if = "Option::is_none")]
    pub hash: Option<String>,
}

impl DenomHashResponse {
    /// QueryDenomHashResponse is the response type for the Query/DenomHash RPC method.
    pub fn new() -> DenomHashResponse {
        DenomHashResponse { hash: None }
    }
}
