/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

/// DenomUnitsRepresentsTheListOfDenomUnitSForAGivenCoinInner : DenomUnit represents a struct that describes a given denomination unit of the basic token.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DenomUnitsRepresentsTheListOfDenomUnitSForAGivenCoinInner {
    /// denom represents the string name of the given denom unit (e.g uatom).
    #[serde(rename = "denom", skip_serializing_if = "Option::is_none")]
    pub denom: Option<String>,
    /// exponent represents power of 10 exponent that one must raise the base_denom to in order to equal the given DenomUnit's denom 1 denom = 1^exponent base_denom (e.g. with a base_denom of uatom, one can create a DenomUnit of 'atom' with exponent = 6, thus: 1 atom = 10^6 uatom).
    #[serde(rename = "exponent", skip_serializing_if = "Option::is_none")]
    pub exponent: Option<i64>,
    #[serde(rename = "aliases", skip_serializing_if = "Option::is_none")]
    pub aliases: Option<Vec<String>>,
}

impl DenomUnitsRepresentsTheListOfDenomUnitSForAGivenCoinInner {
    /// DenomUnit represents a struct that describes a given denomination unit of the basic token.
    pub fn new() -> DenomUnitsRepresentsTheListOfDenomUnitSForAGivenCoinInner {
        DenomUnitsRepresentsTheListOfDenomUnitSForAGivenCoinInner {
            denom: None,
            exponent: None,
            aliases: None,
        }
    }
}
