/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

/// DenomTracesResponse : QueryConnectionsResponse is the response type for the Query/DenomTraces RPC method.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DenomTracesResponse {
    /// denom_traces returns all denominations trace information.
    #[serde(rename = "denom_traces", skip_serializing_if = "Option::is_none")]
    pub denom_traces: Option<Vec<crate::models::DenomTracesResponseDenomTracesInner>>,
    #[serde(rename = "pagination", skip_serializing_if = "Option::is_none")]
    pub pagination: Option<Box<crate::models::AccountsResponsePagination>>,
}

impl DenomTracesResponse {
    /// QueryConnectionsResponse is the response type for the Query/DenomTraces RPC method.
    pub fn new() -> DenomTracesResponse {
        DenomTracesResponse {
            denom_traces: None,
            pagination: None,
        }
    }
}
