/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

/// DenomTraceResponse : QueryDenomTraceResponse is the response type for the Query/DenomTrace RPC method.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DenomTraceResponse {
    #[serde(rename = "denom_trace", skip_serializing_if = "Option::is_none")]
    pub denom_trace: Option<Box<crate::models::DenomTracesResponseDenomTracesInner>>,
}

impl DenomTraceResponse {
    /// QueryDenomTraceResponse is the response type for the Query/DenomTrace RPC method.
    pub fn new() -> DenomTraceResponse {
        DenomTraceResponse { denom_trace: None }
    }
}
