/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

/// DenomsMetadataResponse : QueryDenomsMetadataResponse is the response type for the Query/DenomsMetadata RPC method.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DenomsMetadataResponse {
    /// metadata provides the client information for all the registered tokens.
    #[serde(rename = "metadatas", skip_serializing_if = "Option::is_none")]
    pub metadatas: Option<Vec<crate::models::DenomsMetadataResponseMetadatasInner>>,
    #[serde(rename = "pagination", skip_serializing_if = "Option::is_none")]
    pub pagination: Option<Box<crate::models::AccountsResponsePagination>>,
}

impl DenomsMetadataResponse {
    /// QueryDenomsMetadataResponse is the response type for the Query/DenomsMetadata RPC method.
    pub fn new() -> DenomsMetadataResponse {
        DenomsMetadataResponse {
            metadatas: None,
            pagination: None,
        }
    }
}
