/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Deposit {
    #[serde(rename = "amount", skip_serializing_if = "Option::is_none")]
    pub amount: Option<Vec<crate::models::TxsHashGetResponseTxFeeAmountInner>>,
    #[serde(rename = "proposal_id", skip_serializing_if = "Option::is_none")]
    pub proposal_id: Option<String>,
    /// bech32 encoded address
    #[serde(rename = "depositor", skip_serializing_if = "Option::is_none")]
    pub depositor: Option<String>,
}

impl Deposit {
    pub fn new() -> Deposit {
        Deposit {
            amount: None,
            proposal_id: None,
            depositor: None,
        }
    }
}
