/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

/// EmergencyButtonParamsResponseParams : params defines the parameters of the module.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct EmergencyButtonParamsResponseParams {
    #[serde(rename = "switch_status", skip_serializing_if = "Option::is_none")]
    pub switch_status: Option<String>,
    #[serde(rename = "pauser_address", skip_serializing_if = "Option::is_none")]
    pub pauser_address: Option<String>,
}

impl EmergencyButtonParamsResponseParams {
    /// params defines the parameters of the module.
    pub fn new() -> EmergencyButtonParamsResponseParams {
        EmergencyButtonParamsResponseParams {
            switch_status: None,
            pauser_address: None,
        }
    }
}
