/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct EncryptedSeedResponse {
    #[serde(rename = "encrypted_seed", skip_serializing_if = "Option::is_none")]
    pub encrypted_seed: Option<String>,
}

impl EncryptedSeedResponse {
    pub fn new() -> EncryptedSeedResponse {
        EncryptedSeedResponse {
            encrypted_seed: None,
        }
    }
}
