/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

/// EvidenceResponse : QueryEvidenceResponse is the response type for the Query/Evidence RPC method.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct EvidenceResponse {
    #[serde(rename = "evidence", skip_serializing_if = "Option::is_none")]
    pub evidence: Option<Box<crate::models::AccountsAreTheExistingAccountsInner>>,
}

impl EvidenceResponse {
    /// QueryEvidenceResponse is the response type for the Query/Evidence RPC method.
    pub fn new() -> EvidenceResponse {
        EvidenceResponse { evidence: None }
    }
}
