/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct FeeEnabledChannelContainsThePortIdChannelIdForAFeeEnabledChannel {
    #[serde(rename = "port_id", skip_serializing_if = "Option::is_none")]
    pub port_id: Option<String>,
    #[serde(rename = "channel_id", skip_serializing_if = "Option::is_none")]
    pub channel_id: Option<String>,
}

impl FeeEnabledChannelContainsThePortIdChannelIdForAFeeEnabledChannel {
    pub fn new() -> FeeEnabledChannelContainsThePortIdChannelIdForAFeeEnabledChannel {
        FeeEnabledChannelContainsThePortIdChannelIdForAFeeEnabledChannel {
            port_id: None,
            channel_id: None,
        }
    }
}
