/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

/// FoundationTaxResponse : QueryDelegatorWithdrawAddressResponse is the response type for the Query/DelegatorWithdrawAddress RPC method.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct FoundationTaxResponse {
    /// withdraw_address defines the delegator address to query for.
    #[serde(rename = "tax", skip_serializing_if = "Option::is_none")]
    pub tax: Option<String>,
    #[serde(rename = "foundation_address", skip_serializing_if = "Option::is_none")]
    pub foundation_address: Option<String>,
}

impl FoundationTaxResponse {
    /// QueryDelegatorWithdrawAddressResponse is the response type for the Query/DelegatorWithdrawAddress RPC method.
    pub fn new() -> FoundationTaxResponse {
        FoundationTaxResponse {
            tax: None,
            foundation_address: None,
        }
    }
}
