/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

/// GetLatestBlockResponse : GetLatestBlockResponse is the response type for the Query/GetLatestBlock RPC method.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetLatestBlockResponse {
    #[serde(rename = "block_id", skip_serializing_if = "Option::is_none")]
    pub block_id: Option<Box<crate::models::BlockId1>>,
    #[serde(rename = "block", skip_serializing_if = "Option::is_none")]
    pub block: Option<Box<crate::models::GetLatestBlockResponseBlock>>,
}

impl GetLatestBlockResponse {
    /// GetLatestBlockResponse is the response type for the Query/GetLatestBlock RPC method.
    pub fn new() -> GetLatestBlockResponse {
        GetLatestBlockResponse {
            block_id: None,
            block: None,
        }
    }
}
