/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetNodeInfoResponseDefaultNodeInfo {
    #[serde(rename = "protocol_version", skip_serializing_if = "Option::is_none")]
    pub protocol_version:
        Option<Box<crate::models::GetNodeInfoResponseDefaultNodeInfoProtocolVersion>>,
    #[serde(rename = "default_node_id", skip_serializing_if = "Option::is_none")]
    pub default_node_id: Option<String>,
    #[serde(rename = "listen_addr", skip_serializing_if = "Option::is_none")]
    pub listen_addr: Option<String>,
    #[serde(rename = "network", skip_serializing_if = "Option::is_none")]
    pub network: Option<String>,
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
    #[serde(rename = "channels", skip_serializing_if = "Option::is_none")]
    pub channels: Option<String>,
    #[serde(rename = "moniker", skip_serializing_if = "Option::is_none")]
    pub moniker: Option<String>,
    #[serde(rename = "other", skip_serializing_if = "Option::is_none")]
    pub other: Option<Box<crate::models::GetNodeInfoResponseDefaultNodeInfoOther>>,
}

impl GetNodeInfoResponseDefaultNodeInfo {
    pub fn new() -> GetNodeInfoResponseDefaultNodeInfo {
        GetNodeInfoResponseDefaultNodeInfo {
            protocol_version: None,
            default_node_id: None,
            listen_addr: None,
            network: None,
            version: None,
            channels: None,
            moniker: None,
            other: None,
        }
    }
}
