/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

/// GetSyncingResponse : GetSyncingResponse is the response type for the Query/GetSyncing RPC method.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetSyncingResponse {
    #[serde(rename = "syncing", skip_serializing_if = "Option::is_none")]
    pub syncing: Option<bool>,
}

impl GetSyncingResponse {
    /// GetSyncingResponse is the response type for the Query/GetSyncing RPC method.
    pub fn new() -> GetSyncingResponse {
        GetSyncingResponse { syncing: None }
    }
}
