/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetNodeInfoResponseDefaultNodeInfoProtocolVersion {
    #[serde(rename = "p2p", skip_serializing_if = "Option::is_none")]
    pub p2p: Option<String>,
    #[serde(rename = "block", skip_serializing_if = "Option::is_none")]
    pub block: Option<String>,
    #[serde(rename = "app", skip_serializing_if = "Option::is_none")]
    pub app: Option<String>,
}

impl GetNodeInfoResponseDefaultNodeInfoProtocolVersion {
    pub fn new() -> GetNodeInfoResponseDefaultNodeInfoProtocolVersion {
        GetNodeInfoResponseDefaultNodeInfoProtocolVersion {
            p2p: None,
            block: None,
            app: None,
        }
    }
}
