/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

/// GetTxsEventResponsePagination : pagination defines a pagination for the response.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetTxsEventResponsePagination {
    #[serde(rename = "next_key", skip_serializing_if = "Option::is_none")]
    pub next_key: Option<String>,
    #[serde(rename = "total", skip_serializing_if = "Option::is_none")]
    pub total: Option<String>,
}

impl GetTxsEventResponsePagination {
    /// pagination defines a pagination for the response.
    pub fn new() -> GetTxsEventResponsePagination {
        GetTxsEventResponsePagination {
            next_key: None,
            total: None,
        }
    }
}
