/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

/// GovParamsResponseDepositParams : deposit_params defines the parameters related to deposit.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GovParamsResponseDepositParams {
    /// Minimum deposit for a proposal to enter voting period.
    #[serde(rename = "min_deposit", skip_serializing_if = "Option::is_none")]
    pub min_deposit: Option<Vec<crate::models::AllBalancesResponseBalancesInner>>,
    /// Maximum period for Atom holders to deposit on a proposal. Initial value: 2  months.
    #[serde(rename = "max_deposit_period", skip_serializing_if = "Option::is_none")]
    pub max_deposit_period: Option<String>,
    /// Minimum expedited deposit for a proposal to enter voting period.
    #[serde(
        rename = "min_expedited_deposit",
        skip_serializing_if = "Option::is_none"
    )]
    pub min_expedited_deposit: Option<Vec<crate::models::AllBalancesResponseBalancesInner>>,
}

impl GovParamsResponseDepositParams {
    /// deposit_params defines the parameters related to deposit.
    pub fn new() -> GovParamsResponseDepositParams {
        GovParamsResponseDepositParams {
            min_deposit: None,
            max_deposit_period: None,
            min_expedited_deposit: None,
        }
    }
}
