/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

/// GovParamsResponseVotingParams : voting_params defines the parameters related to voting.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GovParamsResponseVotingParams {
    /// Length of the voting period.
    #[serde(rename = "voting_period", skip_serializing_if = "Option::is_none")]
    pub voting_period: Option<String>,
    /// Length of the expedited voting period.
    #[serde(
        rename = "expedited_voting_period",
        skip_serializing_if = "Option::is_none"
    )]
    pub expedited_voting_period: Option<String>,
}

impl GovParamsResponseVotingParams {
    /// voting_params defines the parameters related to voting.
    pub fn new() -> GovParamsResponseVotingParams {
        GovParamsResponseVotingParams {
            voting_period: None,
            expedited_voting_period: None,
        }
    }
}
