/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

/// GrantIsStoredInTheKvStoreToRecordAGrantWithFullContext : allowance is a allowance granted for grantee by granter.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GrantIsStoredInTheKvStoreToRecordAGrantWithFullContext {
    /// granter is the address of the user granting an allowance of their funds.
    #[serde(rename = "granter", skip_serializing_if = "Option::is_none")]
    pub granter: Option<String>,
    /// grantee is the address of the user being granted an allowance of another user's funds.
    #[serde(rename = "grantee", skip_serializing_if = "Option::is_none")]
    pub grantee: Option<String>,
    #[serde(rename = "allowance", skip_serializing_if = "Option::is_none")]
    pub allowance:
        Option<Box<crate::models::GrantIsStoredInTheKvStoreToRecordAGrantWithFullContextAllowance>>,
}

impl GrantIsStoredInTheKvStoreToRecordAGrantWithFullContext {
    /// allowance is a allowance granted for grantee by granter.
    pub fn new() -> GrantIsStoredInTheKvStoreToRecordAGrantWithFullContext {
        GrantIsStoredInTheKvStoreToRecordAGrantWithFullContext {
            granter: None,
            grantee: None,
            allowance: None,
        }
    }
}
