/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

/// GranterGrantsResponse : QueryGranterGrantsResponse is the response type for the Query/GranterGrants RPC method.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GranterGrantsResponse {
    /// grants is a list of grants granted by the granter.
    #[serde(rename = "grants", skip_serializing_if = "Option::is_none")]
    pub grants: Option<Vec<crate::models::GrantAuthorizationExtendsAGrantWithBothTheAddressesOfTheGranteeAndGranterItIsUsedInGenesisProtoAndQueryProto>>,
    #[serde(rename = "pagination", skip_serializing_if = "Option::is_none")]
    pub pagination: Option<Box<crate::models::GrantsResponsePagination>>,
}

impl GranterGrantsResponse {
    /// QueryGranterGrantsResponse is the response type for the Query/GranterGrants RPC method.
    pub fn new() -> GranterGrantsResponse {
        GranterGrantsResponse {
            grants: None,
            pagination: None,
        }
    }
}
