/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

/// GrantsResponseGrantsInner : Grant gives permissions to execute the provide method with expiration time.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GrantsResponseGrantsInner {
    #[serde(rename = "authorization", skip_serializing_if = "Option::is_none")]
    pub authorization: Option<Box<crate::models::AccountsAreTheExistingAccountsInner>>,
    #[serde(rename = "expiration", skip_serializing_if = "Option::is_none")]
    pub expiration: Option<String>,
}

impl GrantsResponseGrantsInner {
    /// Grant gives permissions to execute the provide method with expiration time.
    pub fn new() -> GrantsResponseGrantsInner {
        GrantsResponseGrantsInner {
            authorization: None,
            expiration: None,
        }
    }
}
