/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

/// HistoricalInfoResponseHist : hist defines the historical info at the given height.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct HistoricalInfoResponseHist {
    #[serde(rename = "header", skip_serializing_if = "Option::is_none")]
    pub header: Option<Box<crate::models::HistoricalInfoResponseHistHeader>>,
    #[serde(rename = "valset", skip_serializing_if = "Option::is_none")]
    pub valset: Option<Vec<crate::models::DelegatorValidatorsInfoResponseValidatorsInner>>,
}

impl HistoricalInfoResponseHist {
    /// hist defines the historical info at the given height.
    pub fn new() -> HistoricalInfoResponseHist {
        HistoricalInfoResponseHist {
            header: None,
            valset: None,
        }
    }
}
