/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

/// IbcApplicationsTransferV1QueryEscrowAddressResponse : QueryEscrowAddressResponse is the response type of the EscrowAddress RPC method.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IbcApplicationsTransferV1QueryEscrowAddressResponse {
    #[serde(rename = "escrow_address", skip_serializing_if = "Option::is_none")]
    pub escrow_address: Option<String>,
}

impl IbcApplicationsTransferV1QueryEscrowAddressResponse {
    /// QueryEscrowAddressResponse is the response type of the EscrowAddress RPC method.
    pub fn new() -> IbcApplicationsTransferV1QueryEscrowAddressResponse {
        IbcApplicationsTransferV1QueryEscrowAddressResponse {
            escrow_address: None,
        }
    }
}
