/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

/// IbcCoreClientV1QueryUpgradedConsensusStateResponse : QueryUpgradedConsensusStateResponse is the response type for the Query/UpgradedConsensusState RPC method.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IbcCoreClientV1QueryUpgradedConsensusStateResponse {
    #[serde(
        rename = "upgraded_consensus_state",
        skip_serializing_if = "Option::is_none"
    )]
    pub upgraded_consensus_state:
        Option<Box<crate::models::ConsensusStateAssociatedWithTheRequestIdentifier>>,
}

impl IbcCoreClientV1QueryUpgradedConsensusStateResponse {
    /// QueryUpgradedConsensusStateResponse is the response type for the Query/UpgradedConsensusState RPC method.
    pub fn new() -> IbcCoreClientV1QueryUpgradedConsensusStateResponse {
        IbcCoreClientV1QueryUpgradedConsensusStateResponse {
            upgraded_consensus_state: None,
        }
    }
}
