/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

/// IbcCoreClientV1QueryClientStatusResponse : QueryClientStatusResponse is the response type for the Query/ClientStatus RPC method. It returns the current status of the IBC client.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IbcCoreClientV1QueryClientStatusResponse {
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
}

impl IbcCoreClientV1QueryClientStatusResponse {
    /// QueryClientStatusResponse is the response type for the Query/ClientStatus RPC method. It returns the current status of the IBC client.
    pub fn new() -> IbcCoreClientV1QueryClientStatusResponse {
        IbcCoreClientV1QueryClientStatusResponse { status: None }
    }
}
