/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IbcApplicationsFeeV1QueryIncentivizedPacketResponse {
    #[serde(
        rename = "incentivized_packet",
        skip_serializing_if = "Option::is_none"
    )]
    pub incentivized_packet: Option<
        Box<crate::models::IdentifiedPacketFeesContainsAListOfTypePacketFeeAndAssociatedPacketId>,
    >,
}

impl IbcApplicationsFeeV1QueryIncentivizedPacketResponse {
    pub fn new() -> IbcApplicationsFeeV1QueryIncentivizedPacketResponse {
        IbcApplicationsFeeV1QueryIncentivizedPacketResponse {
            incentivized_packet: None,
        }
    }
}
