/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

/// IbcCoreChannelV1Order : - ORDER_NONE_UNSPECIFIED: zero-value for channel ordering  - ORDER_UNORDERED: packets can be delivered in any order, which may differ from the order in which they were sent.  - ORDER_ORDERED: packets are delivered exactly in the order which they were sent

/// - ORDER_NONE_UNSPECIFIED: zero-value for channel ordering  - ORDER_UNORDERED: packets can be delivered in any order, which may differ from the order in which they were sent.  - ORDER_ORDERED: packets are delivered exactly in the order which they were sent
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum IbcCoreChannelV1Order {
    #[serde(rename = "ORDER_NONE_UNSPECIFIED")]
    NoneUnspecified,
    #[serde(rename = "ORDER_UNORDERED")]
    Unordered,
    #[serde(rename = "ORDER_ORDERED")]
    Ordered,
}

impl ToString for IbcCoreChannelV1Order {
    fn to_string(&self) -> String {
        match self {
            Self::NoneUnspecified => String::from("ORDER_NONE_UNSPECIFIED"),
            Self::Unordered => String::from("ORDER_UNORDERED"),
            Self::Ordered => String::from("ORDER_ORDERED"),
        }
    }
}

impl Default for IbcCoreChannelV1Order {
    fn default() -> IbcCoreChannelV1Order {
        Self::NoneUnspecified
    }
}
