/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IbcApplicationsFeeV1QueryPayeeResponse {
    #[serde(rename = "payee_address", skip_serializing_if = "Option::is_none")]
    pub payee_address: Option<String>,
}

impl IbcApplicationsFeeV1QueryPayeeResponse {
    pub fn new() -> IbcApplicationsFeeV1QueryPayeeResponse {
        IbcApplicationsFeeV1QueryPayeeResponse {
            payee_address: None,
        }
    }
}
