/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IbcCoreConnectionV1QueryConnectionConsensusStateResponse {
    #[serde(rename = "consensus_state", skip_serializing_if = "Option::is_none")]
    pub consensus_state: Option<Box<crate::models::ConsensusStateAssociatedWithTheChannel>>,
    #[serde(rename = "client_id", skip_serializing_if = "Option::is_none")]
    pub client_id: Option<String>,
    #[serde(rename = "proof", skip_serializing_if = "Option::is_none")]
    pub proof: Option<String>,
    #[serde(rename = "proof_height", skip_serializing_if = "Option::is_none")]
    pub proof_height: Option<Box<crate::models::HeightAtWhichTheProofWasRetrieved>>,
}

impl IbcCoreConnectionV1QueryConnectionConsensusStateResponse {
    pub fn new() -> IbcCoreConnectionV1QueryConnectionConsensusStateResponse {
        IbcCoreConnectionV1QueryConnectionConsensusStateResponse {
            consensus_state: None,
            client_id: None,
            proof: None,
            proof_height: None,
        }
    }
}
