/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

/// IbcCoreClientV1QueryUpgradedClientStateResponse : QueryUpgradedClientStateResponse is the response type for the Query/UpgradedClientState RPC method.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IbcCoreClientV1QueryUpgradedClientStateResponse {
    #[serde(
        rename = "upgraded_client_state",
        skip_serializing_if = "Option::is_none"
    )]
    pub upgraded_client_state:
        Option<Box<crate::models::ClientStateAssociatedWithTheRequestIdentifier>>,
}

impl IbcCoreClientV1QueryUpgradedClientStateResponse {
    /// QueryUpgradedClientStateResponse is the response type for the Query/UpgradedClientState RPC method.
    pub fn new() -> IbcCoreClientV1QueryUpgradedClientStateResponse {
        IbcCoreClientV1QueryUpgradedClientStateResponse {
            upgraded_client_state: None,
        }
    }
}
