/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IbcCoreCommitmentV1MerklePrefix {
    #[serde(rename = "key_prefix", skip_serializing_if = "Option::is_none")]
    pub key_prefix: Option<String>,
}

impl IbcCoreCommitmentV1MerklePrefix {
    pub fn new() -> IbcCoreCommitmentV1MerklePrefix {
        IbcCoreCommitmentV1MerklePrefix { key_prefix: None }
    }
}
