/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IbcApplicationsFeeV1QueryIncentivizedPacketsResponse {
    #[serde(
        rename = "incentivized_packets",
        skip_serializing_if = "Option::is_none"
    )]
    pub incentivized_packets: Option<
        Vec<crate::models::IdentifiedPacketFeesContainsAListOfTypePacketFeeAndAssociatedPacketId>,
    >,
}

impl IbcApplicationsFeeV1QueryIncentivizedPacketsResponse {
    pub fn new() -> IbcApplicationsFeeV1QueryIncentivizedPacketsResponse {
        IbcApplicationsFeeV1QueryIncentivizedPacketsResponse {
            incentivized_packets: None,
        }
    }
}
