/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

/// IbcCoreClientV1QueryClientStateResponse : QueryClientStateResponse is the response type for the Query/ClientState RPC method. Besides the client state, it includes a proof and the height from which the proof was retrieved.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IbcCoreClientV1QueryClientStateResponse {
    #[serde(rename = "client_state", skip_serializing_if = "Option::is_none")]
    pub client_state: Option<Box<crate::models::ClientStateAssociatedWithTheRequestIdentifier>>,
    #[serde(rename = "proof", skip_serializing_if = "Option::is_none")]
    pub proof: Option<String>,
    #[serde(rename = "proof_height", skip_serializing_if = "Option::is_none")]
    pub proof_height: Option<Box<crate::models::HeightAtWhichTheProofWasRetrieved>>,
}

impl IbcCoreClientV1QueryClientStateResponse {
    /// QueryClientStateResponse is the response type for the Query/ClientState RPC method. Besides the client state, it includes a proof and the height from which the proof was retrieved.
    pub fn new() -> IbcCoreClientV1QueryClientStateResponse {
        IbcCoreClientV1QueryClientStateResponse {
            client_state: None,
            proof: None,
            proof_height: None,
        }
    }
}
