/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IbcCoreChannelV1QueryUnreceivedAcksResponse {
    #[serde(rename = "sequences", skip_serializing_if = "Option::is_none")]
    pub sequences: Option<Vec<String>>,
    #[serde(rename = "height", skip_serializing_if = "Option::is_none")]
    pub height: Option<Box<crate::models::QueryBlockHeight>>,
}

impl IbcCoreChannelV1QueryUnreceivedAcksResponse {
    pub fn new() -> IbcCoreChannelV1QueryUnreceivedAcksResponse {
        IbcCoreChannelV1QueryUnreceivedAcksResponse {
            sequences: None,
            height: None,
        }
    }
}
