/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IbcApplicationsFeeV1QueryTotalAckFeesResponse {
    #[serde(rename = "ack_fees", skip_serializing_if = "Option::is_none")]
    pub ack_fees: Option<Vec<crate::models::AllBalancesResponseBalancesInner>>,
}

impl IbcApplicationsFeeV1QueryTotalAckFeesResponse {
    pub fn new() -> IbcApplicationsFeeV1QueryTotalAckFeesResponse {
        IbcApplicationsFeeV1QueryTotalAckFeesResponse { ack_fees: None }
    }
}
