/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IbcApplicationsFeeV1IdentifiedPacketFees {
    #[serde(rename = "packet_id", skip_serializing_if = "Option::is_none")]
    pub packet_id: Option<Box<crate::models::UniquePacketIdentifierComprisedOfTheChannelIdPortIdAndSequence>>,
    #[serde(rename = "packet_fees", skip_serializing_if = "Option::is_none")]
    pub packet_fees: Option<Vec<crate::models::PacketFeeContainsIcs29RelayerFeesRefundAddressAndOptionalListOfPermittedRelayers>>,
}

impl IbcApplicationsFeeV1IdentifiedPacketFees {
    pub fn new() -> IbcApplicationsFeeV1IdentifiedPacketFees {
        IbcApplicationsFeeV1IdentifiedPacketFees {
            packet_id: None,
            packet_fees: None,
        }
    }
}
