/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IbcCoreClientV1QueryConsensusStatesResponse {
    #[serde(rename = "consensus_states", skip_serializing_if = "Option::is_none")]
    pub consensus_states:
        Option<Vec<crate::models::ConsensusStatesAssociatedWithTheIdentifierInner>>,
    #[serde(rename = "pagination", skip_serializing_if = "Option::is_none")]
    pub pagination: Option<Box<crate::models::PaginationResponse>>,
}

impl IbcCoreClientV1QueryConsensusStatesResponse {
    pub fn new() -> IbcCoreClientV1QueryConsensusStatesResponse {
        IbcCoreClientV1QueryConsensusStatesResponse {
            consensus_states: None,
            pagination: None,
        }
    }
}
