/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IbcApplicationsFeeV1QueryCounterpartyPayeeResponse {
    #[serde(rename = "counterparty_payee", skip_serializing_if = "Option::is_none")]
    pub counterparty_payee: Option<String>,
}

impl IbcApplicationsFeeV1QueryCounterpartyPayeeResponse {
    pub fn new() -> IbcApplicationsFeeV1QueryCounterpartyPayeeResponse {
        IbcApplicationsFeeV1QueryCounterpartyPayeeResponse {
            counterparty_payee: None,
        }
    }
}
