/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IbcApplicationsFeeV1QueryTotalTimeoutFeesResponse {
    #[serde(rename = "timeout_fees", skip_serializing_if = "Option::is_none")]
    pub timeout_fees: Option<Vec<crate::models::AllBalancesResponseBalancesInner>>,
}

impl IbcApplicationsFeeV1QueryTotalTimeoutFeesResponse {
    pub fn new() -> IbcApplicationsFeeV1QueryTotalTimeoutFeesResponse {
        IbcApplicationsFeeV1QueryTotalTimeoutFeesResponse { timeout_fees: None }
    }
}
