/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

/// IbcCoreClientV1QueryClientStatesResponse : QueryClientStatesResponse is the response type for the Query/ClientStates RPC method.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IbcCoreClientV1QueryClientStatesResponse {
    /// list of stored ClientStates of the chain.
    #[serde(rename = "client_states", skip_serializing_if = "Option::is_none")]
    pub client_states: Option<Vec<crate::models::ClientStatesResponseClientStatesInner>>,
    #[serde(rename = "pagination", skip_serializing_if = "Option::is_none")]
    pub pagination: Option<Box<crate::models::PaginationResponse>>,
}

impl IbcCoreClientV1QueryClientStatesResponse {
    /// QueryClientStatesResponse is the response type for the Query/ClientStates RPC method.
    pub fn new() -> IbcCoreClientV1QueryClientStatesResponse {
        IbcCoreClientV1QueryClientStatesResponse {
            client_states: None,
            pagination: None,
        }
    }
}
