/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IbcCoreChannelV1QueryConnectionChannelsResponse {
    /// list of channels associated with a connection.
    #[serde(rename = "channels", skip_serializing_if = "Option::is_none")]
    pub channels: Option<Vec<crate::models::ChannelsResponseChannelsInner>>,
    #[serde(rename = "pagination", skip_serializing_if = "Option::is_none")]
    pub pagination: Option<Box<crate::models::PaginationResponse>>,
    #[serde(rename = "height", skip_serializing_if = "Option::is_none")]
    pub height: Option<Box<crate::models::QueryBlockHeight>>,
}

impl IbcCoreChannelV1QueryConnectionChannelsResponse {
    pub fn new() -> IbcCoreChannelV1QueryConnectionChannelsResponse {
        IbcCoreChannelV1QueryConnectionChannelsResponse {
            channels: None,
            pagination: None,
            height: None,
        }
    }
}
