/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

/// IbcApplicationsInterchainAccountsHostV1Params : Params defines the set of on-chain interchain accounts parameters. The following parameters may be used to disable the host submodule.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IbcApplicationsInterchainAccountsHostV1Params {
    /// host_enabled enables or disables the host submodule.
    #[serde(rename = "host_enabled", skip_serializing_if = "Option::is_none")]
    pub host_enabled: Option<bool>,
    /// allow_messages defines a list of sdk message typeURLs allowed to be executed on a host chain.
    #[serde(rename = "allow_messages", skip_serializing_if = "Option::is_none")]
    pub allow_messages: Option<Vec<String>>,
}

impl IbcApplicationsInterchainAccountsHostV1Params {
    /// Params defines the set of on-chain interchain accounts parameters. The following parameters may be used to disable the host submodule.
    pub fn new() -> IbcApplicationsInterchainAccountsHostV1Params {
        IbcApplicationsInterchainAccountsHostV1Params {
            host_enabled: None,
            allow_messages: None,
        }
    }
}
