/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IbcCoreChannelV1QueryPacketAcknowledgementResponse {
    #[serde(rename = "acknowledgement", skip_serializing_if = "Option::is_none")]
    pub acknowledgement: Option<String>,
    #[serde(rename = "proof", skip_serializing_if = "Option::is_none")]
    pub proof: Option<String>,
    #[serde(rename = "proof_height", skip_serializing_if = "Option::is_none")]
    pub proof_height: Option<Box<crate::models::HeightAtWhichTheProofWasRetrieved>>,
}

impl IbcCoreChannelV1QueryPacketAcknowledgementResponse {
    pub fn new() -> IbcCoreChannelV1QueryPacketAcknowledgementResponse {
        IbcCoreChannelV1QueryPacketAcknowledgementResponse {
            acknowledgement: None,
            proof: None,
            proof_height: None,
        }
    }
}
