/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

/// IbcCoreClientV1ConsensusStateWithHeight : ConsensusStateWithHeight defines a consensus state with an additional height field.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IbcCoreClientV1ConsensusStateWithHeight {
    #[serde(rename = "height", skip_serializing_if = "Option::is_none")]
    pub height: Option<Box<crate::models::ConsensusStateHeight>>,
    #[serde(rename = "consensus_state", skip_serializing_if = "Option::is_none")]
    pub consensus_state: Option<Box<crate::models::ConsensusState>>,
}

impl IbcCoreClientV1ConsensusStateWithHeight {
    /// ConsensusStateWithHeight defines a consensus state with an additional height field.
    pub fn new() -> IbcCoreClientV1ConsensusStateWithHeight {
        IbcCoreClientV1ConsensusStateWithHeight {
            height: None,
            consensus_state: None,
        }
    }
}
