/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

/// IbcCoreClientV1Params : Params defines the set of IBC light client parameters.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IbcCoreClientV1Params {
    /// allowed_clients defines the list of allowed client state types.
    #[serde(rename = "allowed_clients", skip_serializing_if = "Option::is_none")]
    pub allowed_clients: Option<Vec<String>>,
}

impl IbcCoreClientV1Params {
    /// Params defines the set of IBC light client parameters.
    pub fn new() -> IbcCoreClientV1Params {
        IbcCoreClientV1Params {
            allowed_clients: None,
        }
    }
}
