/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IdentifiedPacketFeesContainsAListOfTypePacketFeeAndAssociatedPacketId {
    #[serde(rename = "packet_id", skip_serializing_if = "Option::is_none")]
    pub packet_id: Option<Box<crate::models::UniquePacketIdentifierComprisedOfTheChannelIdPortIdAndSequence>>,
    #[serde(rename = "packet_fees", skip_serializing_if = "Option::is_none")]
    pub packet_fees: Option<Vec<crate::models::PacketFeeContainsIcs29RelayerFeesRefundAddressAndOptionalListOfPermittedRelayers>>,
}

impl IdentifiedPacketFeesContainsAListOfTypePacketFeeAndAssociatedPacketId {
    pub fn new() -> IdentifiedPacketFeesContainsAListOfTypePacketFeeAndAssociatedPacketId {
        IdentifiedPacketFeesContainsAListOfTypePacketFeeAndAssociatedPacketId {
            packet_id: None,
            packet_fees: None,
        }
    }
}
