/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ModuleIsTheTypeForVersionInfo {
    #[serde(rename = "path", skip_serializing_if = "Option::is_none")]
    pub path: Option<String>,
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
    #[serde(rename = "sum", skip_serializing_if = "Option::is_none")]
    pub sum: Option<String>,
}

impl ModuleIsTheTypeForVersionInfo {
    pub fn new() -> ModuleIsTheTypeForVersionInfo {
        ModuleIsTheTypeForVersionInfo {
            path: None,
            version: None,
            sum: None,
        }
    }
}
