/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

/// ModuleVersionsResponse : QueryModuleVersionsResponse is the response type for the Query/ModuleVersions RPC method.  Since: cosmos-sdk 0.43

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ModuleVersionsResponse {
    /// module_versions is a list of module names with their consensus versions.
    #[serde(rename = "module_versions", skip_serializing_if = "Option::is_none")]
    pub module_versions: Option<Vec<crate::models::ModuleVersionsResponseModuleVersionsInner>>,
}

impl ModuleVersionsResponse {
    /// QueryModuleVersionsResponse is the response type for the Query/ModuleVersions RPC method.  Since: cosmos-sdk 0.43
    pub fn new() -> ModuleVersionsResponse {
        ModuleVersionsResponse {
            module_versions: None,
        }
    }
}
