/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct MultiRepresentsANestedMultisigSigner {
    #[serde(rename = "bitarray", skip_serializing_if = "Option::is_none")]
    pub bitarray: Option<Box<crate::models::BitarraySpecifiesWhichKeysWithinTheMultisigAreSigning>>,
    #[serde(rename = "mode_infos", skip_serializing_if = "Option::is_none")]
    pub mode_infos: Option<Vec<serde_json::Value>>,
}

impl MultiRepresentsANestedMultisigSigner {
    pub fn new() -> MultiRepresentsANestedMultisigSigner {
        MultiRepresentsANestedMultisigSigner {
            bitarray: None,
            mode_infos: None,
        }
    }
}
