/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PacketFeeContainsIcs29RelayerFeesRefundAddressAndOptionalListOfPermittedRelayers {
    #[serde(rename = "fee", skip_serializing_if = "Option::is_none")]
    pub fee: Option<
        Box<crate::models::FeeEncapsulatesTheRecvAckAndTimeoutFeesAssociatedWithAnIbcPacket>,
    >,
    #[serde(rename = "refund_address", skip_serializing_if = "Option::is_none")]
    pub refund_address: Option<String>,
    #[serde(rename = "relayers", skip_serializing_if = "Option::is_none")]
    pub relayers: Option<Vec<String>>,
}

impl PacketFeeContainsIcs29RelayerFeesRefundAddressAndOptionalListOfPermittedRelayers {
    pub fn new() -> PacketFeeContainsIcs29RelayerFeesRefundAddressAndOptionalListOfPermittedRelayers
    {
        PacketFeeContainsIcs29RelayerFeesRefundAddressAndOptionalListOfPermittedRelayers {
            fee: None,
            refund_address: None,
            relayers: None,
        }
    }
}
