/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

/// PacketforwardV1QueryParamsResponse : QueryParamsResponse is the response type for the Query/Params RPC method.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PacketforwardV1QueryParamsResponse {
    #[serde(rename = "params", skip_serializing_if = "Option::is_none")]
    pub params: Option<Box<crate::models::RouterParamsResponseParams>>,
}

impl PacketforwardV1QueryParamsResponse {
    /// QueryParamsResponse is the response type for the Query/Params RPC method.
    pub fn new() -> PacketforwardV1QueryParamsResponse {
        PacketforwardV1QueryParamsResponse { params: None }
    }
}
