/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

/// PaginationResponse : PageResponse is to be embedded in gRPC response messages where the corresponding request message has used PageRequest.   message SomeResponse {          repeated Bar results = 1;          PageResponse page = 2;  }

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PaginationResponse {
    #[serde(rename = "next_key", skip_serializing_if = "Option::is_none")]
    pub next_key: Option<String>,
    #[serde(rename = "total", skip_serializing_if = "Option::is_none")]
    pub total: Option<String>,
}

impl PaginationResponse {
    /// PageResponse is to be embedded in gRPC response messages where the corresponding request message has used PageRequest.   message SomeResponse {          repeated Bar results = 1;          PageResponse page = 2;  }
    pub fn new() -> PaginationResponse {
        PaginationResponse {
            next_key: None,
            total: None,
        }
    }
}
