/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

/// ParamsResponse : QueryParamsResponse is response type for the Query/Params RPC method.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ParamsResponse {
    #[serde(rename = "param", skip_serializing_if = "Option::is_none")]
    pub param: Option<Box<crate::models::ParamsResponseParam>>,
}

impl ParamsResponse {
    /// QueryParamsResponse is response type for the Query/Params RPC method.
    pub fn new() -> ParamsResponse {
        ParamsResponse { param: None }
    }
}
