/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

/// ParamsResponseParam : param defines the queried parameter.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ParamsResponseParam {
    #[serde(rename = "subspace", skip_serializing_if = "Option::is_none")]
    pub subspace: Option<String>,
    #[serde(rename = "key", skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
}

impl ParamsResponseParam {
    /// param defines the queried parameter.
    pub fn new() -> ParamsResponseParam {
        ParamsResponseParam {
            subspace: None,
            key: None,
            value: None,
        }
    }
}
