/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

/// PoolResponsePool : pool defines the pool info.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PoolResponsePool {
    #[serde(rename = "not_bonded_tokens", skip_serializing_if = "Option::is_none")]
    pub not_bonded_tokens: Option<String>,
    #[serde(rename = "bonded_tokens", skip_serializing_if = "Option::is_none")]
    pub bonded_tokens: Option<String>,
}

impl PoolResponsePool {
    /// pool defines the pool info.
    pub fn new() -> PoolResponsePool {
        PoolResponsePool {
            not_bonded_tokens: None,
            bonded_tokens: None,
        }
    }
}
