/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

/// ProposalsResponseProposalsInner : Proposal defines the core field members of a governance proposal.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProposalsResponseProposalsInner {
    #[serde(rename = "proposal_id", skip_serializing_if = "Option::is_none")]
    pub proposal_id: Option<String>,
    #[serde(rename = "content", skip_serializing_if = "Option::is_none")]
    pub content: Option<Box<crate::models::AccountsAreTheExistingAccountsInner>>,
    /// ProposalStatus enumerates the valid statuses of a proposal.   - PROPOSAL_STATUS_UNSPECIFIED: PROPOSAL_STATUS_UNSPECIFIED defines the default propopsal status.  - PROPOSAL_STATUS_DEPOSIT_PERIOD: PROPOSAL_STATUS_DEPOSIT_PERIOD defines a proposal status during the deposit period.  - PROPOSAL_STATUS_VOTING_PERIOD: PROPOSAL_STATUS_VOTING_PERIOD defines a proposal status during the voting period.  - PROPOSAL_STATUS_PASSED: PROPOSAL_STATUS_PASSED defines a proposal status of a proposal that has passed.  - PROPOSAL_STATUS_REJECTED: PROPOSAL_STATUS_REJECTED defines a proposal status of a proposal that has been rejected.  - PROPOSAL_STATUS_FAILED: PROPOSAL_STATUS_FAILED defines a proposal status of a proposal that has failed.
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<Status>,
    #[serde(rename = "final_tally_result", skip_serializing_if = "Option::is_none")]
    pub final_tally_result:
        Option<Box<crate::models::ProposalsResponseProposalsInnerFinalTallyResult>>,
    #[serde(rename = "submit_time", skip_serializing_if = "Option::is_none")]
    pub submit_time: Option<String>,
    #[serde(rename = "deposit_end_time", skip_serializing_if = "Option::is_none")]
    pub deposit_end_time: Option<String>,
    #[serde(rename = "total_deposit", skip_serializing_if = "Option::is_none")]
    pub total_deposit: Option<Vec<crate::models::AllBalancesResponseBalancesInner>>,
    #[serde(rename = "voting_start_time", skip_serializing_if = "Option::is_none")]
    pub voting_start_time: Option<String>,
    #[serde(rename = "voting_end_time", skip_serializing_if = "Option::is_none")]
    pub voting_end_time: Option<String>,
    #[serde(rename = "is_expedited", skip_serializing_if = "Option::is_none")]
    pub is_expedited: Option<bool>,
}

impl ProposalsResponseProposalsInner {
    /// Proposal defines the core field members of a governance proposal.
    pub fn new() -> ProposalsResponseProposalsInner {
        ProposalsResponseProposalsInner {
            proposal_id: None,
            content: None,
            status: None,
            final_tally_result: None,
            submit_time: None,
            deposit_end_time: None,
            total_deposit: None,
            voting_start_time: None,
            voting_end_time: None,
            is_expedited: None,
        }
    }
}

/// ProposalStatus enumerates the valid statuses of a proposal.   - PROPOSAL_STATUS_UNSPECIFIED: PROPOSAL_STATUS_UNSPECIFIED defines the default propopsal status.  - PROPOSAL_STATUS_DEPOSIT_PERIOD: PROPOSAL_STATUS_DEPOSIT_PERIOD defines a proposal status during the deposit period.  - PROPOSAL_STATUS_VOTING_PERIOD: PROPOSAL_STATUS_VOTING_PERIOD defines a proposal status during the voting period.  - PROPOSAL_STATUS_PASSED: PROPOSAL_STATUS_PASSED defines a proposal status of a proposal that has passed.  - PROPOSAL_STATUS_REJECTED: PROPOSAL_STATUS_REJECTED defines a proposal status of a proposal that has been rejected.  - PROPOSAL_STATUS_FAILED: PROPOSAL_STATUS_FAILED defines a proposal status of a proposal that has failed.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "PROPOSAL_STATUS_UNSPECIFIED")]
    Unspecified,
    #[serde(rename = "PROPOSAL_STATUS_DEPOSIT_PERIOD")]
    DepositPeriod,
    #[serde(rename = "PROPOSAL_STATUS_VOTING_PERIOD")]
    VotingPeriod,
    #[serde(rename = "PROPOSAL_STATUS_PASSED")]
    Passed,
    #[serde(rename = "PROPOSAL_STATUS_REJECTED")]
    Rejected,
    #[serde(rename = "PROPOSAL_STATUS_FAILED")]
    Failed,
}

impl Default for Status {
    fn default() -> Status {
        Self::Unspecified
    }
}
