/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

/// ProposalResponse : QueryProposalResponse is the response type for the Query/Proposal RPC method.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProposalResponse {
    #[serde(rename = "proposal", skip_serializing_if = "Option::is_none")]
    pub proposal: Option<Box<crate::models::ProposalsResponseProposalsInner>>,
}

impl ProposalResponse {
    /// QueryProposalResponse is the response type for the Query/Proposal RPC method.
    pub fn new() -> ProposalResponse {
        ProposalResponse { proposal: None }
    }
}
