/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct QueryPacketCommitmentsResponseIsTheRequestTypeForTheQueryQueryPacketCommitmentsRpcMethod {
    #[serde(rename = "commitments", skip_serializing_if = "Option::is_none")]
    pub commitments: Option<Vec<crate::models::QueryPacketAcknowledgemetsResponseIsTheRequestTypeForTheQueryQueryPacketAcknowledgementsRpcMethodAcknowledgementsInner>>,
    #[serde(rename = "pagination", skip_serializing_if = "Option::is_none")]
    pub pagination: Option<Box<crate::models::PaginationResponse>>,
    #[serde(rename = "height", skip_serializing_if = "Option::is_none")]
    pub height: Option<Box<crate::models::QueryBlockHeight>>,
}

impl QueryPacketCommitmentsResponseIsTheRequestTypeForTheQueryQueryPacketCommitmentsRpcMethod {
    pub fn new(
    ) -> QueryPacketCommitmentsResponseIsTheRequestTypeForTheQueryQueryPacketCommitmentsRpcMethod
    {
        QueryPacketCommitmentsResponseIsTheRequestTypeForTheQueryQueryPacketCommitmentsRpcMethod {
            commitments: None,
            pagination: None,
            height: None,
        }
    }
}
