/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

/// QueryContractHistoryResponseIsTheResponseTypeForTheQueryContractHistoryRpcMethodEntriesInner : ContractCodeHistoryEntry metadata to a contract.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct QueryContractHistoryResponseIsTheResponseTypeForTheQueryContractHistoryRpcMethodEntriesInner
{
    /// - CONTRACT_CODE_HISTORY_OPERATION_TYPE_UNSPECIFIED: ContractCodeHistoryOperationTypeUnspecified placeholder for empty value  - CONTRACT_CODE_HISTORY_OPERATION_TYPE_INIT: ContractCodeHistoryOperationTypeInit on chain contract instantiation  - CONTRACT_CODE_HISTORY_OPERATION_TYPE_MIGRATE: ContractCodeHistoryOperationTypeMigrate code migration  - CONTRACT_CODE_HISTORY_OPERATION_TYPE_GENESIS: ContractCodeHistoryOperationTypeGenesis based on genesis data
    #[serde(rename = "operation", skip_serializing_if = "Option::is_none")]
    pub operation: Option<Operation>,
    #[serde(rename = "code_id", skip_serializing_if = "Option::is_none")]
    pub code_id: Option<String>,
    #[serde(rename = "updated", skip_serializing_if = "Option::is_none")]
    pub updated: Option<Box<crate::models::AbsoluteTxPositionCanBeUsedToSortContracts>>,
    #[serde(rename = "msg", skip_serializing_if = "Option::is_none")]
    pub msg: Option<String>,
}

impl QueryContractHistoryResponseIsTheResponseTypeForTheQueryContractHistoryRpcMethodEntriesInner {
    /// ContractCodeHistoryEntry metadata to a contract.
    pub fn new(
    ) -> QueryContractHistoryResponseIsTheResponseTypeForTheQueryContractHistoryRpcMethodEntriesInner
    {
        QueryContractHistoryResponseIsTheResponseTypeForTheQueryContractHistoryRpcMethodEntriesInner {
            operation: None,
            code_id: None,
            updated: None,
            msg: None,
        }
    }
}

/// - CONTRACT_CODE_HISTORY_OPERATION_TYPE_UNSPECIFIED: ContractCodeHistoryOperationTypeUnspecified placeholder for empty value  - CONTRACT_CODE_HISTORY_OPERATION_TYPE_INIT: ContractCodeHistoryOperationTypeInit on chain contract instantiation  - CONTRACT_CODE_HISTORY_OPERATION_TYPE_MIGRATE: ContractCodeHistoryOperationTypeMigrate code migration  - CONTRACT_CODE_HISTORY_OPERATION_TYPE_GENESIS: ContractCodeHistoryOperationTypeGenesis based on genesis data
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Operation {
    #[serde(rename = "CONTRACT_CODE_HISTORY_OPERATION_TYPE_UNSPECIFIED")]
    Unspecified,
    #[serde(rename = "CONTRACT_CODE_HISTORY_OPERATION_TYPE_INIT")]
    Init,
    #[serde(rename = "CONTRACT_CODE_HISTORY_OPERATION_TYPE_MIGRATE")]
    Migrate,
    #[serde(rename = "CONTRACT_CODE_HISTORY_OPERATION_TYPE_GENESIS")]
    Genesis,
}

impl Default for Operation {
    fn default() -> Operation {
        Self::Unspecified
    }
}
