/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct QueryConsensusStateHeightsResponseIsTheResponseTypeForTheQueryConsensusStateHeightsRpcMethod {
    #[serde(rename = "consensus_state_heights", skip_serializing_if = "Option::is_none")]
    pub consensus_state_heights: Option<Vec<crate::models::HeightIsAMonotonicallyIncreasingDataTypeThatCanBeComparedAgainstAnotherHeightForThePurposesOfUpdatingAndFreezingClients>>,
    #[serde(rename = "pagination", skip_serializing_if = "Option::is_none")]
    pub pagination: Option<Box<crate::models::PaginationResponse>>,
}

impl QueryConsensusStateHeightsResponseIsTheResponseTypeForTheQueryConsensusStateHeightsRpcMethod {
    pub fn new(
    ) -> QueryConsensusStateHeightsResponseIsTheResponseTypeForTheQueryConsensusStateHeightsRpcMethod
    {
        QueryConsensusStateHeightsResponseIsTheResponseTypeForTheQueryConsensusStateHeightsRpcMethod {
            consensus_state_heights: None,
            pagination: None,
        }
    }
}
