/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct QueryConsensusStatesResponseIsTheResponseTypeForTheQueryConsensusStatesRpcMethod {
    #[serde(rename = "consensus_states", skip_serializing_if = "Option::is_none")]
    pub consensus_states:
        Option<Vec<crate::models::ConsensusStatesAssociatedWithTheIdentifierInner>>,
    #[serde(rename = "pagination", skip_serializing_if = "Option::is_none")]
    pub pagination: Option<Box<crate::models::PaginationResponse>>,
}

impl QueryConsensusStatesResponseIsTheResponseTypeForTheQueryConsensusStatesRpcMethod {
    pub fn new() -> QueryConsensusStatesResponseIsTheResponseTypeForTheQueryConsensusStatesRpcMethod
    {
        QueryConsensusStatesResponseIsTheResponseTypeForTheQueryConsensusStatesRpcMethod {
            consensus_states: None,
            pagination: None,
        }
    }
}
