/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct QueryValidatorDelegationsResponseIsResponseTypeForTheQueryValidatorDelegationsRpcMethod {
    #[serde(
        rename = "delegation_responses",
        skip_serializing_if = "Option::is_none"
    )]
    pub delegation_responses:
        Option<Vec<crate::models::DelegatorDelegationsResponseDelegationResponsesInner>>,
    #[serde(rename = "pagination", skip_serializing_if = "Option::is_none")]
    pub pagination: Option<Box<crate::models::AccountsResponsePagination>>,
}

impl QueryValidatorDelegationsResponseIsResponseTypeForTheQueryValidatorDelegationsRpcMethod {
    pub fn new(
    ) -> QueryValidatorDelegationsResponseIsResponseTypeForTheQueryValidatorDelegationsRpcMethod
    {
        QueryValidatorDelegationsResponseIsResponseTypeForTheQueryValidatorDelegationsRpcMethod {
            delegation_responses: None,
            pagination: None,
        }
    }
}
