/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct QueryContractInfoResponseIsTheResponseTypeForTheQueryContractInfoRpcMethod {
    #[serde(rename = "contract_address", skip_serializing_if = "Option::is_none")]
    pub contract_address: Option<String>,
    #[serde(rename = "contract_info", skip_serializing_if = "Option::is_none")]
    pub contract_info: Option<Box<crate::models::ContractInfoStoresAWasmContractInstance>>,
}

impl QueryContractInfoResponseIsTheResponseTypeForTheQueryContractInfoRpcMethod {
    pub fn new() -> QueryContractInfoResponseIsTheResponseTypeForTheQueryContractInfoRpcMethod {
        QueryContractInfoResponseIsTheResponseTypeForTheQueryContractInfoRpcMethod {
            contract_address: None,
            contract_info: None,
        }
    }
}
