/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct QueryInterchainAccountFromAddressResponseTheResponseTypeForTheQueryInterchainAccountAddressRpc
{
    #[serde(
        rename = "interchain_account_address",
        skip_serializing_if = "Option::is_none"
    )]
    pub interchain_account_address: Option<String>,
}

impl
    QueryInterchainAccountFromAddressResponseTheResponseTypeForTheQueryInterchainAccountAddressRpc
{
    pub fn new() -> QueryInterchainAccountFromAddressResponseTheResponseTypeForTheQueryInterchainAccountAddressRpc{
        QueryInterchainAccountFromAddressResponseTheResponseTypeForTheQueryInterchainAccountAddressRpc {
            interchain_account_address: None,
        }
    }
}
