/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct QueryFeeEnabledChannelsResponseDefinesTheResponseTypeForTheFeeEnabledChannelsRpc {
    #[serde(
        rename = "fee_enabled_channels",
        skip_serializing_if = "Option::is_none"
    )]
    pub fee_enabled_channels: Option<
        Vec<crate::models::FeeEnabledChannelContainsThePortIdChannelIdForAFeeEnabledChannel>,
    >,
}

impl QueryFeeEnabledChannelsResponseDefinesTheResponseTypeForTheFeeEnabledChannelsRpc {
    pub fn new() -> QueryFeeEnabledChannelsResponseDefinesTheResponseTypeForTheFeeEnabledChannelsRpc
    {
        QueryFeeEnabledChannelsResponseDefinesTheResponseTypeForTheFeeEnabledChannelsRpc {
            fee_enabled_channels: None,
        }
    }
}
