/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct RedelegationEntry {
    #[serde(rename = "creation_height", skip_serializing_if = "Option::is_none")]
    pub creation_height: Option<i32>,
    #[serde(rename = "completion_time", skip_serializing_if = "Option::is_none")]
    pub completion_time: Option<i32>,
    #[serde(rename = "initial_balance", skip_serializing_if = "Option::is_none")]
    pub initial_balance: Option<String>,
    #[serde(rename = "balance", skip_serializing_if = "Option::is_none")]
    pub balance: Option<String>,
    #[serde(rename = "shares_dst", skip_serializing_if = "Option::is_none")]
    pub shares_dst: Option<String>,
}

impl RedelegationEntry {
    pub fn new() -> RedelegationEntry {
        RedelegationEntry {
            creation_height: None,
            completion_time: None,
            initial_balance: None,
            balance: None,
            shares_dst: None,
        }
    }
}
