/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Redelegation {
    #[serde(rename = "delegator_address", skip_serializing_if = "Option::is_none")]
    pub delegator_address: Option<String>,
    #[serde(
        rename = "validator_src_address",
        skip_serializing_if = "Option::is_none"
    )]
    pub validator_src_address: Option<String>,
    #[serde(
        rename = "validator_dst_address",
        skip_serializing_if = "Option::is_none"
    )]
    pub validator_dst_address: Option<String>,
    #[serde(rename = "entries", skip_serializing_if = "Option::is_none")]
    pub entries: Option<Vec<crate::models::Redelegation>>,
}

impl Redelegation {
    pub fn new() -> Redelegation {
        Redelegation {
            delegator_address: None,
            validator_src_address: None,
            validator_dst_address: None,
            entries: None,
        }
    }
}
