/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

/// RestakingEntriesResponse : QueryRestakeThresholdResponse is the request type for the Query/Params RPC method.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct RestakingEntriesResponse {
    #[serde(rename = "validators", skip_serializing_if = "Option::is_none")]
    pub validators: Option<Vec<String>>,
}

impl RestakingEntriesResponse {
    /// QueryRestakeThresholdResponse is the request type for the Query/Params RPC method.
    pub fn new() -> RestakingEntriesResponse {
        RestakingEntriesResponse { validators: None }
    }
}
