/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

/// RestakeThresholdResponse : QueryRestakeThresholdResponse is the request type for the Query/Params RPC method.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct RestakeThresholdResponse {
    #[serde(rename = "threshold", skip_serializing_if = "Option::is_none")]
    pub threshold: Option<String>,
}

impl RestakeThresholdResponse {
    /// QueryRestakeThresholdResponse is the request type for the Query/Params RPC method.
    pub fn new() -> RestakeThresholdResponse {
        RestakeThresholdResponse { threshold: None }
    }
}
