/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

/// SecretEmergencybuttonV1beta1Params : Params defines the parameters for the ibc-rate-limit module.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SecretEmergencybuttonV1beta1Params {
    #[serde(rename = "switch_status", skip_serializing_if = "Option::is_none")]
    pub switch_status: Option<String>,
    #[serde(rename = "pauser_address", skip_serializing_if = "Option::is_none")]
    pub pauser_address: Option<String>,
}

impl SecretEmergencybuttonV1beta1Params {
    /// Params defines the parameters for the ibc-rate-limit module.
    pub fn new() -> SecretEmergencybuttonV1beta1Params {
        SecretEmergencybuttonV1beta1Params {
            switch_status: None,
            pauser_address: None,
        }
    }
}
