/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

/// SecretEmergencybuttonV1beta1ParamsResponse : ParamsResponse is the response type for the Query/Params RPC method.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SecretEmergencybuttonV1beta1ParamsResponse {
    #[serde(rename = "params", skip_serializing_if = "Option::is_none")]
    pub params: Option<Box<crate::models::EmergencyButtonParamsResponseParams>>,
}

impl SecretEmergencybuttonV1beta1ParamsResponse {
    /// ParamsResponse is the response type for the Query/Params RPC method.
    pub fn new() -> SecretEmergencybuttonV1beta1ParamsResponse {
        SecretEmergencybuttonV1beta1ParamsResponse { params: None }
    }
}
