/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

/// SecretComputeV1beta1ContractCodeHistoryOperationType : - CONTRACT_CODE_HISTORY_OPERATION_TYPE_UNSPECIFIED: ContractCodeHistoryOperationTypeUnspecified placeholder for empty value  - CONTRACT_CODE_HISTORY_OPERATION_TYPE_INIT: ContractCodeHistoryOperationTypeInit on chain contract instantiation  - CONTRACT_CODE_HISTORY_OPERATION_TYPE_MIGRATE: ContractCodeHistoryOperationTypeMigrate code migration  - CONTRACT_CODE_HISTORY_OPERATION_TYPE_GENESIS: ContractCodeHistoryOperationTypeGenesis based on genesis data

/// - CONTRACT_CODE_HISTORY_OPERATION_TYPE_UNSPECIFIED: ContractCodeHistoryOperationTypeUnspecified placeholder for empty value  - CONTRACT_CODE_HISTORY_OPERATION_TYPE_INIT: ContractCodeHistoryOperationTypeInit on chain contract instantiation  - CONTRACT_CODE_HISTORY_OPERATION_TYPE_MIGRATE: ContractCodeHistoryOperationTypeMigrate code migration  - CONTRACT_CODE_HISTORY_OPERATION_TYPE_GENESIS: ContractCodeHistoryOperationTypeGenesis based on genesis data
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SecretComputeV1beta1ContractCodeHistoryOperationType {
    #[serde(rename = "CONTRACT_CODE_HISTORY_OPERATION_TYPE_UNSPECIFIED")]
    Unspecified,
    #[serde(rename = "CONTRACT_CODE_HISTORY_OPERATION_TYPE_INIT")]
    Init,
    #[serde(rename = "CONTRACT_CODE_HISTORY_OPERATION_TYPE_MIGRATE")]
    Migrate,
    #[serde(rename = "CONTRACT_CODE_HISTORY_OPERATION_TYPE_GENESIS")]
    Genesis,
}

impl ToString for SecretComputeV1beta1ContractCodeHistoryOperationType {
    fn to_string(&self) -> String {
        match self {
            Self::Unspecified => String::from("CONTRACT_CODE_HISTORY_OPERATION_TYPE_UNSPECIFIED"),
            Self::Init => String::from("CONTRACT_CODE_HISTORY_OPERATION_TYPE_INIT"),
            Self::Migrate => String::from("CONTRACT_CODE_HISTORY_OPERATION_TYPE_MIGRATE"),
            Self::Genesis => String::from("CONTRACT_CODE_HISTORY_OPERATION_TYPE_GENESIS"),
        }
    }
}

impl Default for SecretComputeV1beta1ContractCodeHistoryOperationType {
    fn default() -> SecretComputeV1beta1ContractCodeHistoryOperationType {
        Self::Unspecified
    }
}
