/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SecretComputeV1beta1QueryCodesResponse {
    #[serde(rename = "code_infos", skip_serializing_if = "Option::is_none")]
    pub code_infos: Option<Vec<crate::models::CodeResponseCodeInfo>>,
}

impl SecretComputeV1beta1QueryCodesResponse {
    pub fn new() -> SecretComputeV1beta1QueryCodesResponse {
        SecretComputeV1beta1QueryCodesResponse { code_infos: None }
    }
}
