/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SecretComputeV1beta1QueryContractsByCodeIdResponse {
    #[serde(rename = "contract_infos", skip_serializing_if = "Option::is_none")]
    pub contract_infos: Option<Vec<crate::models::ContractInfoWithAddressAddsTheContractAddressToTheContractInfoRepresentation>>,
}

impl SecretComputeV1beta1QueryContractsByCodeIdResponse {
    pub fn new() -> SecretComputeV1beta1QueryContractsByCodeIdResponse {
        SecretComputeV1beta1QueryContractsByCodeIdResponse {
            contract_infos: None,
        }
    }
}
