/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SecretComputeV1beta1QueryContractAddressResponse {
    #[serde(rename = "contract_address", skip_serializing_if = "Option::is_none")]
    pub contract_address: Option<String>,
}

impl SecretComputeV1beta1QueryContractAddressResponse {
    pub fn new() -> SecretComputeV1beta1QueryContractAddressResponse {
        SecretComputeV1beta1QueryContractAddressResponse {
            contract_address: None,
        }
    }
}
