/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SecretComputeV1beta1QuerySecretContractResponse {
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<String>,
}

impl SecretComputeV1beta1QuerySecretContractResponse {
    pub fn new() -> SecretComputeV1beta1QuerySecretContractResponse {
        SecretComputeV1beta1QuerySecretContractResponse { data: None }
    }
}
