/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SecretComputeV1beta1CodeInfoResponse {
    #[serde(rename = "code_id", skip_serializing_if = "Option::is_none")]
    pub code_id: Option<String>,
    #[serde(rename = "creator", skip_serializing_if = "Option::is_none")]
    pub creator: Option<String>,
    #[serde(rename = "code_hash", skip_serializing_if = "Option::is_none")]
    pub code_hash: Option<String>,
    #[serde(rename = "source", skip_serializing_if = "Option::is_none")]
    pub source: Option<String>,
    #[serde(rename = "builder", skip_serializing_if = "Option::is_none")]
    pub builder: Option<String>,
}

impl SecretComputeV1beta1CodeInfoResponse {
    pub fn new() -> SecretComputeV1beta1CodeInfoResponse {
        SecretComputeV1beta1CodeInfoResponse {
            code_id: None,
            creator: None,
            code_hash: None,
            source: None,
            builder: None,
        }
    }
}
