/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

/// SimulateRequest : SimulateRequest is the request type for the Service.Simulate RPC method.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SimulateRequest {
    #[serde(rename = "tx", skip_serializing_if = "Option::is_none")]
    pub tx: Option<Box<crate::models::SimulateRequestTx>>,
    /// tx_bytes is the raw transaction.  Since: cosmos-sdk 0.43
    #[serde(rename = "tx_bytes", skip_serializing_if = "Option::is_none")]
    pub tx_bytes: Option<String>,
}

impl SimulateRequest {
    /// SimulateRequest is the request type for the Service.Simulate RPC method.
    pub fn new() -> SimulateRequest {
        SimulateRequest {
            tx: None,
            tx_bytes: None,
        }
    }
}
