/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

/// StakingParamsResponse : QueryParamsResponse is response type for the Query/Params RPC method.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct StakingParamsResponse {
    #[serde(rename = "params", skip_serializing_if = "Option::is_none")]
    pub params: Option<Box<crate::models::StakingParamsResponseParams>>,
}

impl StakingParamsResponse {
    /// QueryParamsResponse is response type for the Query/Params RPC method.
    pub fn new() -> StakingParamsResponse {
        StakingParamsResponse { params: None }
    }
}
