/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

/// TendermintTypesSignedMsgType : SignedMsgType is a type of signed message in the consensus.   - SIGNED_MSG_TYPE_PREVOTE: Votes  - SIGNED_MSG_TYPE_PROPOSAL: Proposals

/// SignedMsgType is a type of signed message in the consensus.   - SIGNED_MSG_TYPE_PREVOTE: Votes  - SIGNED_MSG_TYPE_PROPOSAL: Proposals
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TendermintTypesSignedMsgType {
    #[serde(rename = "SIGNED_MSG_TYPE_UNKNOWN")]
    Unknown,
    #[serde(rename = "SIGNED_MSG_TYPE_PREVOTE")]
    Prevote,
    #[serde(rename = "SIGNED_MSG_TYPE_PRECOMMIT")]
    Precommit,
    #[serde(rename = "SIGNED_MSG_TYPE_PROPOSAL")]
    Proposal,
}

impl ToString for TendermintTypesSignedMsgType {
    fn to_string(&self) -> String {
        match self {
            Self::Unknown => String::from("SIGNED_MSG_TYPE_UNKNOWN"),
            Self::Prevote => String::from("SIGNED_MSG_TYPE_PREVOTE"),
            Self::Precommit => String::from("SIGNED_MSG_TYPE_PRECOMMIT"),
            Self::Proposal => String::from("SIGNED_MSG_TYPE_PROPOSAL"),
        }
    }
}

impl Default for TendermintTypesSignedMsgType {
    fn default() -> TendermintTypesSignedMsgType {
        Self::Unknown
    }
}
