/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TendermintCryptoPublicKey {
    #[serde(rename = "ed25519", skip_serializing_if = "Option::is_none")]
    pub ed25519: Option<String>,
    #[serde(rename = "secp256k1", skip_serializing_if = "Option::is_none")]
    pub secp256k1: Option<String>,
}

impl TendermintCryptoPublicKey {
    pub fn new() -> TendermintCryptoPublicKey {
        TendermintCryptoPublicKey {
            ed25519: None,
            secp256k1: None,
        }
    }
}
