/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TendermintTypesBlockIdFlag {
    #[serde(rename = "BLOCK_ID_FLAG_UNKNOWN")]
    Unknown,
    #[serde(rename = "BLOCK_ID_FLAG_ABSENT")]
    Absent,
    #[serde(rename = "BLOCK_ID_FLAG_COMMIT")]
    Commit,
    #[serde(rename = "BLOCK_ID_FLAG_NIL")]
    Nil,
}

impl ToString for TendermintTypesBlockIdFlag {
    fn to_string(&self) -> String {
        match self {
            Self::Unknown => String::from("BLOCK_ID_FLAG_UNKNOWN"),
            Self::Absent => String::from("BLOCK_ID_FLAG_ABSENT"),
            Self::Commit => String::from("BLOCK_ID_FLAG_COMMIT"),
            Self::Nil => String::from("BLOCK_ID_FLAG_NIL"),
        }
    }
}

impl Default for TendermintTypesBlockIdFlag {
    fn default() -> TendermintTypesBlockIdFlag {
        Self::Unknown
    }
}
