/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

/// TendermintAbciEvent : Event allows application developers to attach additional information to ResponseBeginBlock, ResponseEndBlock, ResponseCheckTx and ResponseDeliverTx. Later, transactions may be queried using these events.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TendermintAbciEvent {
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    #[serde(rename = "attributes", skip_serializing_if = "Option::is_none")]
    pub attributes: Option<Vec<crate::models::SimulateResponseResultEventsInnerAttributesInner>>,
}

impl TendermintAbciEvent {
    /// Event allows application developers to attach additional information to ResponseBeginBlock, ResponseEndBlock, ResponseCheckTx and ResponseDeliverTx. Later, transactions may be queried using these events.
    pub fn new() -> TendermintAbciEvent {
        TendermintAbciEvent {
            r#type: None,
            attributes: None,
        }
    }
}
