/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

/// TendermintAbciEventAttribute : EventAttribute is a single key-value pair, associated with an event.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TendermintAbciEventAttribute {
    #[serde(rename = "key", skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
    #[serde(rename = "index", skip_serializing_if = "Option::is_none")]
    pub index: Option<bool>,
}

impl TendermintAbciEventAttribute {
    /// EventAttribute is a single key-value pair, associated with an event.
    pub fn new() -> TendermintAbciEventAttribute {
        TendermintAbciEventAttribute {
            key: None,
            value: None,
            index: None,
        }
    }
}
