/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

/// UpgradedConsensusStateLastHeightResponse : QueryUpgradedConsensusStateResponse is the response type for the Query/UpgradedConsensusState RPC method.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpgradedConsensusStateLastHeightResponse {
    #[serde(
        rename = "upgraded_consensus_state",
        skip_serializing_if = "Option::is_none"
    )]
    pub upgraded_consensus_state: Option<String>,
}

impl UpgradedConsensusStateLastHeightResponse {
    /// QueryUpgradedConsensusStateResponse is the response type for the Query/UpgradedConsensusState RPC method.
    pub fn new() -> UpgradedConsensusStateLastHeightResponse {
        UpgradedConsensusStateLastHeightResponse {
            upgraded_consensus_state: None,
        }
    }
}
