/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

/// ValidatorSlashesResponse : QueryValidatorSlashesResponse is the response type for the Query/ValidatorSlashes RPC method.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ValidatorSlashesResponse {
    /// slashes defines the slashes the validator received.
    #[serde(rename = "slashes", skip_serializing_if = "Option::is_none")]
    pub slashes: Option<Vec<crate::models::ValidatorSlashesResponseSlashesInner>>,
    #[serde(rename = "pagination", skip_serializing_if = "Option::is_none")]
    pub pagination: Option<Box<crate::models::AccountsResponsePagination>>,
}

impl ValidatorSlashesResponse {
    /// QueryValidatorSlashesResponse is the response type for the Query/ValidatorSlashes RPC method.
    pub fn new() -> ValidatorSlashesResponse {
        ValidatorSlashesResponse {
            slashes: None,
            pagination: None,
        }
    }
}
