/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

/// ValidatorOutstandingRewardsResponseRewards : ValidatorOutstandingRewards represents outstanding (un-withdrawn) rewards for a validator inexpensive to track, allows simple sanity checks.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ValidatorOutstandingRewardsResponseRewards {
    #[serde(rename = "rewards", skip_serializing_if = "Option::is_none")]
    pub rewards: Option<Vec<crate::models::CommunityPoolResponsePoolInner>>,
}

impl ValidatorOutstandingRewardsResponseRewards {
    /// ValidatorOutstandingRewards represents outstanding (un-withdrawn) rewards for a validator inexpensive to track, allows simple sanity checks.
    pub fn new() -> ValidatorOutstandingRewardsResponseRewards {
        ValidatorOutstandingRewardsResponseRewards { rewards: None }
    }
}
