/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

/// ValidatorUnbondingDelegationsResponse : QueryValidatorUnbondingDelegationsResponse is response type for the Query/ValidatorUnbondingDelegations RPC method.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ValidatorUnbondingDelegationsResponse {
    #[serde(
        rename = "unbonding_responses",
        skip_serializing_if = "Option::is_none"
    )]
    pub unbonding_responses:
        Option<Vec<crate::models::DelegatorUnbondingDelegationsResponseUnbondingResponsesInner>>,
    #[serde(rename = "pagination", skip_serializing_if = "Option::is_none")]
    pub pagination: Option<Box<crate::models::AccountsResponsePagination>>,
}

impl ValidatorUnbondingDelegationsResponse {
    /// QueryValidatorUnbondingDelegationsResponse is response type for the Query/ValidatorUnbondingDelegations RPC method.
    pub fn new() -> ValidatorUnbondingDelegationsResponse {
        ValidatorUnbondingDelegationsResponse {
            unbonding_responses: None,
            pagination: None,
        }
    }
}
