/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

/// ValidatorOutstandingRewardsResponse : QueryValidatorOutstandingRewardsResponse is the response type for the Query/ValidatorOutstandingRewards RPC method.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ValidatorOutstandingRewardsResponse {
    #[serde(rename = "rewards", skip_serializing_if = "Option::is_none")]
    pub rewards: Option<Box<crate::models::ValidatorOutstandingRewardsResponseRewards>>,
}

impl ValidatorOutstandingRewardsResponse {
    /// QueryValidatorOutstandingRewardsResponse is the response type for the Query/ValidatorOutstandingRewards RPC method.
    pub fn new() -> ValidatorOutstandingRewardsResponse {
        ValidatorOutstandingRewardsResponse { rewards: None }
    }
}
