/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Validator {
    /// bech32 encoded address
    #[serde(rename = "operator_address", skip_serializing_if = "Option::is_none")]
    pub operator_address: Option<String>,
    #[serde(rename = "consensus_pubkey", skip_serializing_if = "Option::is_none")]
    pub consensus_pubkey: Option<String>,
    #[serde(rename = "jailed", skip_serializing_if = "Option::is_none")]
    pub jailed: Option<bool>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<i32>,
    #[serde(rename = "tokens", skip_serializing_if = "Option::is_none")]
    pub tokens: Option<String>,
    #[serde(rename = "delegator_shares", skip_serializing_if = "Option::is_none")]
    pub delegator_shares: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<
        Box<crate::models::StakingDelegatorsDelegatorAddrValidatorsGetResponseInnerDescription>,
    >,
    #[serde(rename = "bond_height", skip_serializing_if = "Option::is_none")]
    pub bond_height: Option<String>,
    #[serde(
        rename = "bond_intra_tx_counter",
        skip_serializing_if = "Option::is_none"
    )]
    pub bond_intra_tx_counter: Option<i32>,
    #[serde(rename = "unbonding_height", skip_serializing_if = "Option::is_none")]
    pub unbonding_height: Option<String>,
    #[serde(rename = "unbonding_time", skip_serializing_if = "Option::is_none")]
    pub unbonding_time: Option<String>,
    #[serde(rename = "commission", skip_serializing_if = "Option::is_none")]
    pub commission: Option<
        Box<crate::models::StakingDelegatorsDelegatorAddrValidatorsGetResponseInnerCommission>,
    >,
}

impl Validator {
    pub fn new() -> Validator {
        Validator {
            operator_address: None,
            consensus_pubkey: None,
            jailed: None,
            status: None,
            tokens: None,
            delegator_shares: None,
            description: None,
            bond_height: None,
            bond_intra_tx_counter: None,
            unbonding_height: None,
            unbonding_time: None,
            commission: None,
        }
    }
}
