/*
 * Secret Network
 *
 * A REST interface for queries and transactions
 *
 * The version of the OpenAPI document: v1.12
 *
 * Generated by: https://openapi-generator.tech
 */

/// VotesResponse : QueryVotesResponse is the response type for the Query/Votes RPC method.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct VotesResponse {
    /// votes defined the queried votes.
    #[serde(rename = "votes", skip_serializing_if = "Option::is_none")]
    pub votes: Option<Vec<crate::models::VotesResponseVotesInner>>,
    #[serde(rename = "pagination", skip_serializing_if = "Option::is_none")]
    pub pagination: Option<Box<crate::models::AccountsResponsePagination>>,
}

impl VotesResponse {
    /// QueryVotesResponse is the response type for the Query/Votes RPC method.
    pub fn new() -> VotesResponse {
        VotesResponse {
            votes: None,
            pagination: None,
        }
    }
}
