name: Workspace

on:
  push:
    branches: main
    paths-ignore:
      - README.md
  pull_request:
    paths-ignore:
      - README.md

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -Dwarnings
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"

jobs:
  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mozilla-actions/sccache-action@v0.0.4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.72.0
          components: rustfmt
      - run: cargo fmt --all -- --check

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mozilla-actions/sccache-action@v0.0.4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.72.0
          components: clippy
      - run: cargo clippy --all --all-features -- -D warnings
